import { createBacklinkOutreachDraftTemplate } from "./outreachDraftTemplate";

type Attempt = { id: string; outreach_id: string; attempt_kind: string; status: string; created_at: string };
type Outreach = { id: string; campaign_id: string; contact_id: string };
type Draft = { id: string; attempt_id: string; follow_up_number: number; subject: string; body: string; prepared_at: string; updated_at: string; updated_by: string };
export class BacklinkOutreachFollowUpDraftError extends Error { constructor(public readonly code: "FOLLOW_UP_DRAFT_ATTEMPT_NOT_PREPARED" | "FOLLOW_UP_DRAFT_CONFLICT" | "FOLLOW_UP_DRAFT_INVALID") { super(code); } }
export type BacklinkOutreachFollowUpDraftDependencies = { getAttempt(workspaceId: string, attemptId: string): Promise<Attempt>; getOutreach(workspaceId: string, outreachId: string): Promise<Outreach>; listAttempts(workspaceId: string, outreachId: string): Promise<Attempt[]>; getTemplateData(workspaceId: string, outreach: Outreach): Promise<{ campaign: { name: string; objective: string }; contact: { fullName: string | null; roleTitle: string | null }; domain: { hostname: string }; opportunity: { targetPageTitle: string; targetPageUrl: string; opportunityType: string; pageType: string; evidenceSummary: string }; asset: { displayName: string; canonicalUrl: string | null } }>; getDraft(workspaceId: string, attemptId: string): Promise<Draft | null>; prepare(input: { workspaceId: string; outreachId: string; attemptId: string; actorUserId: string; subject: string; body: string; preparedAt: string }): Promise<Draft & { disposition: "created" | "existing" }>; update(input: { workspaceId: string; outreachId: string; attemptId: string; actorUserId: string; subject: string; body: string; expectedUpdatedAt: string; updatedAt: string }): Promise<Draft>; now?: () => string };
function valid(attempt: Attempt, outreachId: string) { return attempt.outreach_id === outreachId && attempt.attempt_kind === "follow_up" && attempt.status === "prepared"; }
function content(value: string, max: number) { const result = value.trim(); if (!result || result.length > max) throw new BacklinkOutreachFollowUpDraftError("FOLLOW_UP_DRAFT_INVALID"); return result; }
export function prepareBacklinkOutreachFollowUpDraft(deps: BacklinkOutreachFollowUpDraftDependencies) { return async (input: { workspaceId: string; outreachId: string; attemptId: string; actorUserId: string }) => { const attempt = await deps.getAttempt(input.workspaceId, input.attemptId); if (!valid(attempt, input.outreachId)) throw new BacklinkOutreachFollowUpDraftError("FOLLOW_UP_DRAFT_ATTEMPT_NOT_PREPARED"); const existing = await deps.getDraft(input.workspaceId, attempt.id); if (existing != null) return { ...existing, disposition: "existing" as const }; const outreach = await deps.getOutreach(input.workspaceId, input.outreachId); const attempts = await deps.listAttempts(input.workspaceId, outreach.id); const followUpNumber = attempts.filter((item) => item.attempt_kind === "follow_up" && (item.created_at < attempt.created_at || item.id <= attempt.id)).length; const data = await deps.getTemplateData(input.workspaceId, outreach); const template = createBacklinkOutreachDraftTemplate({ ...data, channel: "email", mode: "follow_up", followUpNumber }); return deps.prepare({ ...input, subject: content(template.subject ?? "", 300), body: content(template.body, 10000), preparedAt: (deps.now ?? (() => new Date().toISOString()))() }); }; }
export function updateBacklinkOutreachFollowUpDraft(deps: BacklinkOutreachFollowUpDraftDependencies) { return async (input: { workspaceId: string; outreachId: string; attemptId: string; actorUserId: string; subject: string; body: string; expectedUpdatedAt: string }) => { const attempt = await deps.getAttempt(input.workspaceId, input.attemptId); if (!valid(attempt, input.outreachId)) throw new BacklinkOutreachFollowUpDraftError("FOLLOW_UP_DRAFT_ATTEMPT_NOT_PREPARED"); try { return await deps.update({ ...input, subject: content(input.subject, 300), body: content(input.body, 10000), updatedAt: (deps.now ?? (() => new Date().toISOString()))() }); } catch (error) { if (error instanceof BacklinkOutreachFollowUpDraftError) throw error; throw error; } }; }
