import { createKnowledgeRegistry } from "./registry";
import type { KnowledgeObject } from "./types";

export const ExampleKnowledgeObject: KnowledgeObject = {
  identity: {
    canonicalId: "example.knowledge-object",
    canonicalName: "Example Knowledge Object",
    aliases: [],
    abbreviations: [],
    translations: {},
    parentConcepts: [],
    childConcepts: [],
    siblingConcepts: [],
    relatedConcepts: [],
    status: "draft",
    version: "0.1.0",
    owner: "Example owner",
    evidenceLevel: "E0",
  },
  definition: {
    shortDefinition: "A non-domain example used to exercise the knowledge contract.",
    purpose: "Demonstrate typing, validation, registry, and graph behavior without modelling a business concept.",
    scope: ["Knowledge Engine foundation"],
    outOfScope: ["Public content", "Business concepts"],
    commonMisunderstandings: [],
    terminologyNotes: [],
    calculationRelevance: "Not applicable.",
    businessRelevance: "Not applicable.",
    unitsAndDimensions: [],
    formulaReferences: [],
    conventionVariants: [],
  },
  evidence: {
    primarySources: [],
    secondarySources: [],
    internalMethodologyReferences: [],
    citationRules: ["No claims are projected from this example."],
    externalReferences: [],
    internalReferences: [],
    limitations: ["This object is not a real domain concept."],
    contradictoryEvidence: [],
  },
  relationships: {
    requires: [],
    dependsOn: [],
    relatedTo: [],
    oftenConfusedWith: [],
    opposite: [],
    derivedFrom: [],
    uses: [],
    usedBy: [],
    calculatorReferences: [],
    guideReferences: [],
    articleReferences: [],
    researchReferences: [],
    apiReferences: [],
  },
  editorialProjections: [],
  structuredKnowledge: {
    canonicalUrls: [],
    entity: "Example entity",
    entityType: "example",
    schemaSuitability: "not_applicable",
    schemaTypes: [],
    secondaryKeywords: [],
    semanticKeywords: [],
    localeCoverage: {},
    internalImportance: "low",
    retrievalEligibility: "excluded",
    apiEligibility: "excluded",
  },
  internalLinking: {
    requiredInboundLinks: [],
    requiredOutboundLinks: [],
    anchorGuidance: [],
    canonicalDestinations: [],
    linkRationales: [],
    duplicationGuard: "Not applicable for the example object.",
    projectionSpecificRules: [],
  },
  quality: {
    requiredChecks: ["Type validation", "Registry validation"],
    privacyReview: "not_applicable",
    translationReview: "not_applicable",
    structuredDataReview: "not_applicable",
  },
  lifecycle: {
    stateHistory: [
      {
        status: "draft",
        date: "2026-07-24",
        reason: "Created as a non-domain contract example.",
      },
    ],
    reviewFrequency: "Not applicable for the example object.",
    versionHistory: ["0.1.0"],
    breakingChangePolicy: "Replace the example rather than treating it as a public contract.",
    ownershipTransferHistory: [],
  },
};

export function createExampleKnowledgeRegistry() {
  return createKnowledgeRegistry([ExampleKnowledgeObject]);
}
