import { formatEditorialAuditReport, maxDisplayedIssues } from "./format-report";
import { runFullEditorialAudit } from "./full-audit";
import type { EditorialAuditReport } from "./types";

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

function clusterSection(output: string, topicId: `topic:${string}`): string {
  const start = output.indexOf(topicId);
  assert(start >= 0, `${topicId} must be formatted.`);
  const end = output.indexOf("\n\n", start);
  return output.slice(start, end >= 0 ? end : undefined);
}

export function runEditorialAuditReportFormatterSmokeTest(): void {
  const report = runFullEditorialAudit();
  const reportSnapshot = JSON.stringify(report);
  const output = formatEditorialAuditReport(report);
  const pricing = clusterSection(output, "topic:pricing");
  const revenue = clusterSection(output, "topic:revenue");
  const photos = clusterSection(output, "topic:photos");

  assert(output.includes("Norixo Editorial Audit") && output.includes("Schema: 1") && output.includes("Generated by: norixo-editorial-audit"), "The formatter must include the audit header.");
  assert(!/\d{4}-\d{2}-\d{2}/.test(output), "The formatter must not include a runtime date.");
  assert(pricing.includes("Readiness: READY"), "Pricing must be formatted as ready.");
  assert(revenue.includes("Readiness: READY"), "Revenue must be formatted as ready.");
  assert(photos.includes("Readiness: OVERLOADED"), "Photos must be formatted as overloaded.");
  assert(output.includes("Governance:") && output.includes("Coverage:") && output.includes("Content:") && output.includes("Resolver eligible nodes:") && output.includes("Resolver nodes with links:") && output.includes("Resolver average links:"), "The formatter must include available cluster metrics.");
  assert(output.includes("Orphans:") && output.includes("Duplicate mappings:") && output.includes("Cannibalization analyzed pairs:") && output.includes("Cannibalization signaled pairs:") && output.includes("Cannibalization high-signal pairs:"), "The formatter must include the global summary.");
  assert(output.includes(`Issues (${report.issues.length})`), "The formatter must display the total issue count.");
  assert(output.split("\n").filter((line) => line.startsWith("  [")).length <= maxDisplayedIssues, "The formatter must limit detailed issues.");
  if (report.issues.length > maxDisplayedIssues) {
    assert(output.includes(`... and ${report.issues.length - maxDisplayedIssues} more issues`), "The formatter must display issue overflow.");
  }
  assert(!output.includes("undefined"), "The formatter must not render undefined values.");
  assert(formatEditorialAuditReport(report) === output, "The formatter must be deterministic.");
  assert(JSON.stringify(report) === reportSnapshot, "The formatter must not mutate the report.");

  const noIssuesReport: EditorialAuditReport = {
    schemaVersion: "1",
    generatedBy: "norixo-editorial-audit",
    clusters: [],
    issues: [],
    diagnostics: { unknown_future_module: { anything: true } },
  };
  const noIssuesOutput = formatEditorialAuditReport(noIssuesReport);
  assert(noIssuesOutput.includes("No issues."), "A report without issues must be formatted explicitly.");
  assert(!noIssuesOutput.includes("unknown_future_module") && !noIssuesOutput.includes('{"anything":true}'), "Unknown diagnostics must not be dumped.");

  console.log("Editorial audit report formatter smoke passed.");
  console.log(output.split("\n").slice(0, 12).join("\n"));
}
