import type { EditorialCannibalizationMetrics } from "./cannibalization";
import type { EditorialAuditReport, EditorialClusterAudit } from "./types";

export const maxDisplayedIssues = 20;

interface ClusterSummary {
  topicId: `topic:${string}`;
  readiness?: EditorialClusterAudit["readiness"];
  inventory?: NonNullable<EditorialClusterAudit["inventory"]>;
  resolverMetrics?: unknown;
  coverage?: unknown;
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function isCannibalizationMetrics(value: unknown): value is EditorialCannibalizationMetrics {
  return isObject(value)
    && typeof value.analyzedArticles === "number"
    && typeof value.analyzedPairs === "number"
    && typeof value.signaledPairs === "number"
    && typeof value.highSignalPairs === "number";
}

function clusterSummaries(clusters: readonly EditorialClusterAudit[]): ClusterSummary[] {
  const summaries = new Map<`topic:${string}`, ClusterSummary>();

  clusters.forEach((cluster) => {
    const summary = summaries.get(cluster.topicId) ?? { topicId: cluster.topicId };
    if (cluster.readiness !== undefined) summary.readiness = cluster.readiness;
    if (cluster.inventory !== undefined) summary.inventory = cluster.inventory;
    if (cluster.resolverMetrics !== undefined) summary.resolverMetrics = cluster.resolverMetrics;
    if (cluster.coverage !== undefined) summary.coverage = cluster.coverage;
    summaries.set(cluster.topicId, summary);
  });

  return [...summaries.values()];
}

function readinessLabel(readiness: EditorialClusterAudit["readiness"]): string {
  return readiness ? readiness.toUpperCase() : "n/a";
}

function addIfNumber(lines: string[], label: string, value: unknown): void {
  if (typeof value === "number") lines.push(`  ${label}: ${value}`);
}

function formatCluster(summary: ClusterSummary): string[] {
  const lines = [summary.topicId, `  Readiness: ${readinessLabel(summary.readiness)}`];
  const coverage = isObject(summary.coverage) ? summary.coverage : undefined;
  const resolverMetrics = isObject(summary.resolverMetrics) ? summary.resolverMetrics : undefined;

  if (typeof coverage?.governanceStatus === "string") lines.push(`  Governance: ${coverage.governanceStatus}`);
  if (typeof coverage?.coverageStatus === "string") lines.push(`  Coverage: ${coverage.coverageStatus}`);
  if (summary.inventory) {
    lines.push(`  Content: ${summary.inventory.total}`);
    (["article", "guide", "tool", "solution"] as const).forEach((contentType) => {
      lines.push(`  ${contentType[0].toUpperCase()}${contentType.slice(1)}s: ${summary.inventory!.byType[contentType]}`);
    });
  }
  addIfNumber(lines, "Resolver eligible nodes", resolverMetrics?.eligibleNodes);
  addIfNumber(lines, "Resolver nodes with links", resolverMetrics?.nodesWithLinks);
  addIfNumber(lines, "Resolver average links", resolverMetrics?.averageLinks);

  return lines;
}

export function formatEditorialAuditReport(report: EditorialAuditReport): string {
  const lines = [
    "Norixo Editorial Audit",
    "",
    `Schema: ${report.schemaVersion}`,
    `Generated by: ${report.generatedBy}`,
    "",
    "Clusters",
  ];
  const summaries = clusterSummaries(report.clusters);

  if (summaries.length === 0) {
    lines.push("No clusters.");
  } else {
    summaries.forEach((summary, index) => {
      if (index > 0) lines.push("");
      lines.push(...formatCluster(summary));
    });
  }

  const orphanCount = report.issues.filter((issue) => issue.code === "orphan_content_node").length;
  const duplicateMappingCount = report.issues.filter((issue) => issue.code === "duplicate_mapping").length;
  const cannibalization = report.diagnostics.cannibalization;
  lines.push("", "Global", `  Orphans: ${orphanCount}`, `  Duplicate mappings: ${duplicateMappingCount}`);
  if (isCannibalizationMetrics(cannibalization)) {
    lines.push(`  Cannibalization analyzed pairs: ${cannibalization.analyzedPairs}`);
    lines.push(`  Cannibalization signaled pairs: ${cannibalization.signaledPairs}`);
    lines.push(`  Cannibalization high-signal pairs: ${cannibalization.highSignalPairs}`);
  }

  lines.push("", `Issues (${report.issues.length})`);
  if (report.issues.length === 0) {
    lines.push("No issues.");
  } else {
    report.issues.slice(0, maxDisplayedIssues).forEach((issue) => {
      const scope = [issue.clusterId && `cluster=${issue.clusterId}`, issue.nodeId && `node=${issue.nodeId}`]
        .filter(Boolean)
        .join(" ");
      lines.push(`  [${issue.severity.toUpperCase()}] ${issue.code}: ${issue.message}${scope ? ` (${scope})` : ""}`);
    });
    if (report.issues.length > maxDisplayedIssues) {
      lines.push(`... and ${report.issues.length - maxDisplayedIssues} more issues`);
    }
  }

  return lines.join("\n");
}
