import { NextRequest, NextResponse } from "next/server";
import { isAdminPrivateEmail } from "@/lib/auth/isAdminEmail";
import { addOpportunityToCampaign, listCampaignOpportunities } from "@/lib/backlinks/services/campaignService";
import { getRequestUserAndWorkspace } from "@/lib/server/routeAuth";

const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function errorResponse(error: unknown) { const code = typeof error === "object" && error != null && "code" in error && typeof error.code === "string" ? error.code : null; const message = error instanceof Error ? error.message : "Impossible de traiter les associations."; return NextResponse.json({ error: message }, { status: code === "NOT_FOUND" ? 404 : code === "VALIDATION" ? 400 : code === "CONFLICT" ? 409 : code === "FORBIDDEN" ? 403 : 500 }); }
async function context(request: NextRequest) { const result = await getRequestUserAndWorkspace(request); if (!result.client || !result.user || !result.workspace) return null; return isAdminPrivateEmail(result.user.email) ? { client: result.client, user: result.user, workspace: result.workspace } : "forbidden" as const; }
export async function GET(request: NextRequest, contextValue: { params: Promise<{ id: string }> }) { const { id } = await contextValue.params; const requestContext = await context(request); if (requestContext == null) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (requestContext === "forbidden") return NextResponse.json({ error: "Forbidden" }, { status: 403 }); if (!uuid.test(id)) return NextResponse.json({ error: "Invalid campaign id" }, { status: 400 }); try { return NextResponse.json(await listCampaignOpportunities(requestContext.client, requestContext.workspace.id, id)); } catch (error) { return errorResponse(error); } }
export async function POST(request: NextRequest, contextValue: { params: Promise<{ id: string }> }) { const { id } = await contextValue.params; const requestContext = await context(request); if (requestContext == null) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (requestContext === "forbidden") return NextResponse.json({ error: "Forbidden" }, { status: 403 }); if (!uuid.test(id)) return NextResponse.json({ error: "Invalid campaign id" }, { status: 400 }); const body: unknown = await request.json().catch(() => null); if (typeof body !== "object" || body == null || Array.isArray(body) || !("opportunity_id" in body) || typeof body.opportunity_id !== "string" || !uuid.test(body.opportunity_id)) return NextResponse.json({ error: "Invalid request body" }, { status: 400 }); try { return NextResponse.json(await addOpportunityToCampaign(requestContext.client, requestContext.workspace.id, requestContext.user.id, id, body.opportunity_id, {}), { status: 201 }); } catch (error) { return errorResponse(error); } }
