import { NextRequest, NextResponse } from "next/server";
import { isAdminPrivateEmail } from "@/lib/auth/isAdminEmail";
import { getBacklinkOutreachById, getActiveBacklinkOutreachByIdentity, listBacklinkOutreachByOpportunity, updateBacklinkOutreach } from "@/lib/backlinks/repositories/outreachRepository";
import { getCampaignOpportunity } from "@/lib/backlinks/repositories/campaignOpportunitiesRepository";
import { getBacklinkOpportunityById } from "@/lib/backlinks/repositories/opportunitiesRepository";
import { listBacklinkContactsByDomain } from "@/lib/backlinks/repositories/contactsRepository";
import { markBacklinkOutreachReady } from "@/lib/backlinks/services/outreachReadyService";
import { getRequestUserAndWorkspace } from "@/lib/server/routeAuth";
export async function POST(request: NextRequest, context: { params: Promise<{ id: string }> }) { const auth = await getRequestUserAndWorkspace(request); if (auth.status === "unauthenticated") return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (auth.status === "workspace_forbidden" || !isAdminPrivateEmail(auth.user.email)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const body: unknown = await request.json().catch(() => null); if (typeof body !== "object" || body == null || Array.isArray(body) || Object.keys(body).length !== 1 || !("confirm" in body) || body.confirm !== true) return NextResponse.json({ error: "Invalid request body" }, { status: 400 }); const { id } = await context.params; try { const result = await markBacklinkOutreachReady({ eligibility: { getMembership: (v) => getCampaignOpportunity(auth.client, v.workspaceId, v.campaignId, v.opportunityId), getOpportunity: (w, o) => getBacklinkOpportunityById(auth.client, w, o), listContactsByDomain: (w, d) => listBacklinkContactsByDomain(auth.client, w, d), listOutreachByOpportunity: (w, o) => listBacklinkOutreachByOpportunity(auth.client, w, o) }, getOutreach: (w, o) => getBacklinkOutreachById(auth.client, w, o), getActiveOutreach: (v) => getActiveBacklinkOutreachByIdentity(auth.client, v), updateOutreach: (w, o, v) => updateBacklinkOutreach(auth.client, w, o, v) })({ workspaceId: auth.workspace.id, actorUserId: auth.user.id, outreachId: id }); return NextResponse.json({ ok: true, result }); } catch { return NextResponse.json({ error: "Ready approval unavailable." }, { status: 409 }); } }
