export const INTELLIGENCE_V2_FACT_CONTRACT_VERSION = "v1";
export const INTELLIGENCE_V2_TRANSFORMATION_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_ELIGIBILITY_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_DEDUPLICATION_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_MARKET_CELL_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_CONFIDENCE_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_FRESHNESS_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_PRICING_NORMALIZATION_POLICY_VERSION = "v1";

export const INTELLIGENCE_V2_POLICY_VERSIONS = Object.freeze({
  factContractVersion: INTELLIGENCE_V2_FACT_CONTRACT_VERSION,
  transformationPolicyVersion: INTELLIGENCE_V2_TRANSFORMATION_POLICY_VERSION,
  eligibilityPolicyVersion: INTELLIGENCE_V2_ELIGIBILITY_POLICY_VERSION,
  deduplicationPolicyVersion: INTELLIGENCE_V2_DEDUPLICATION_POLICY_VERSION,
  marketCellPolicyVersion: INTELLIGENCE_V2_MARKET_CELL_POLICY_VERSION,
  confidencePolicyVersion: INTELLIGENCE_V2_CONFIDENCE_POLICY_VERSION,
  freshnessPolicyVersion: INTELLIGENCE_V2_FRESHNESS_POLICY_VERSION,
  pricingNormalizationPolicyVersion:
    INTELLIGENCE_V2_PRICING_NORMALIZATION_POLICY_VERSION,
} as const);
