export const INTELLIGENCE_V2_FACT_CONTRACT_VERSION = "v1";
export const INTELLIGENCE_V2_BENCHMARK_ARTIFACT_CONTRACT_VERSION = "v1";
export const INTELLIGENCE_V2_PRICING_BENCHMARK_EVIDENCE_CONTRACT_VERSION = "v1";
export const INTELLIGENCE_V2_BENCHMARK_GOVERNANCE_CONTRACT_VERSION = "v1";
export const INTELLIGENCE_V2_TRANSFORMATION_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_ELIGIBILITY_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_DEDUPLICATION_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_MARKET_CELL_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_BENCHMARK_SELECTION_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_BENCHMARK_FALLBACK_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_BENCHMARK_QUALITY_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_BENCHMARK_USAGE_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_CONFIDENCE_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_FRESHNESS_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_PRICING_NORMALIZATION_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_COHORT_DEFINITION_VERSION = "v1";
export const INTELLIGENCE_V2_COHORT_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_AGGREGATION_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_OUTLIER_POLICY_VERSION = "v1";
export const INTELLIGENCE_V2_APPROVAL_POLICY_VERSION = "v1";

export const INTELLIGENCE_V2_POLICY_VERSIONS = Object.freeze({
  factContractVersion: INTELLIGENCE_V2_FACT_CONTRACT_VERSION,
  benchmarkArtifactContractVersion:
    INTELLIGENCE_V2_BENCHMARK_ARTIFACT_CONTRACT_VERSION,
  pricingBenchmarkEvidenceContractVersion:
    INTELLIGENCE_V2_PRICING_BENCHMARK_EVIDENCE_CONTRACT_VERSION,
  benchmarkGovernanceContractVersion:
    INTELLIGENCE_V2_BENCHMARK_GOVERNANCE_CONTRACT_VERSION,
  transformationPolicyVersion: INTELLIGENCE_V2_TRANSFORMATION_POLICY_VERSION,
  eligibilityPolicyVersion: INTELLIGENCE_V2_ELIGIBILITY_POLICY_VERSION,
  deduplicationPolicyVersion: INTELLIGENCE_V2_DEDUPLICATION_POLICY_VERSION,
  marketCellPolicyVersion: INTELLIGENCE_V2_MARKET_CELL_POLICY_VERSION,
  benchmarkSelectionPolicyVersion:
    INTELLIGENCE_V2_BENCHMARK_SELECTION_POLICY_VERSION,
  benchmarkFallbackPolicyVersion:
    INTELLIGENCE_V2_BENCHMARK_FALLBACK_POLICY_VERSION,
  benchmarkQualityPolicyVersion:
    INTELLIGENCE_V2_BENCHMARK_QUALITY_POLICY_VERSION,
  benchmarkUsagePolicyVersion:
    INTELLIGENCE_V2_BENCHMARK_USAGE_POLICY_VERSION,
  confidencePolicyVersion: INTELLIGENCE_V2_CONFIDENCE_POLICY_VERSION,
  freshnessPolicyVersion: INTELLIGENCE_V2_FRESHNESS_POLICY_VERSION,
  pricingNormalizationPolicyVersion:
    INTELLIGENCE_V2_PRICING_NORMALIZATION_POLICY_VERSION,
  cohortDefinitionVersion: INTELLIGENCE_V2_COHORT_DEFINITION_VERSION,
  cohortPolicyVersion: INTELLIGENCE_V2_COHORT_POLICY_VERSION,
  aggregationPolicyVersion: INTELLIGENCE_V2_AGGREGATION_POLICY_VERSION,
  outlierPolicyVersion: INTELLIGENCE_V2_OUTLIER_POLICY_VERSION,
  approvalPolicyVersion: INTELLIGENCE_V2_APPROVAL_POLICY_VERSION,
} as const);
