import { NextRequest, NextResponse } from "next/server";
import { isAdminPrivateEmail } from "@/lib/auth/isAdminEmail";
import { getAsset, updateAsset, type AssetUpdateInput } from "@/lib/backlinks/services/assetService";
import { getRequestUserAndWorkspace } from "@/lib/server/routeAuth";
function isRecord(body: unknown): body is Record<string, unknown> { return typeof body === "object" && body != null && !Array.isArray(body); }
function value(body: Record<string, unknown>, key: string) { const candidate = body[key]; return typeof candidate === "string" ? candidate : undefined; }
function errorResponse(error: unknown) { const code = typeof error === "object" && error != null && "code" in error && typeof error.code === "string" ? error.code : null; const message = error instanceof Error ? error.message : "Impossible de traiter l’asset."; return NextResponse.json({ error: message }, { status: code === "NOT_FOUND" ? 404 : code === "VALIDATION" ? 400 : code === "CONFLICT" ? 409 : code === "FORBIDDEN" ? 403 : 500 }); }
async function context(request: NextRequest) { const result = await getRequestUserAndWorkspace(request); if (!result.client || !result.user || !result.workspace) return null; return isAdminPrivateEmail(result.user.email) ? { client: result.client, user: result.user, workspace: result.workspace } : "forbidden" as const; }
function input(body: Record<string, unknown>): AssetUpdateInput { return { ...(value(body, "display_name") !== undefined ? { display_name: value(body, "display_name") } : {}), ...(value(body, "asset_type") !== undefined ? { asset_type: value(body, "asset_type") } : {}), ...(value(body, "description") !== undefined ? { description: value(body, "description") } : {}), ...(value(body, "canonical_url") !== undefined ? { canonical_url: value(body, "canonical_url") } : {}), ...(value(body, "lifecycle_status") !== undefined ? { lifecycle_status: value(body, "lifecycle_status") } : {}) }; }
export async function GET(request: NextRequest, contextValue: { params: Promise<{ id: string }> }) { const { id } = await contextValue.params; const requestContext = await context(request); if (requestContext == null) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (requestContext === "forbidden") return NextResponse.json({ error: "Forbidden" }, { status: 403 }); try { return NextResponse.json(await getAsset(requestContext.client, requestContext.workspace.id, id)); } catch (error) { return errorResponse(error); } }
export async function PATCH(request: NextRequest, contextValue: { params: Promise<{ id: string }> }) { const { id } = await contextValue.params; const requestContext = await context(request); if (requestContext == null) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (requestContext === "forbidden") return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const body: unknown = await request.json().catch(() => null); if (!isRecord(body)) return NextResponse.json({ error: "Invalid request body" }, { status: 400 }); try { return NextResponse.json(await updateAsset(requestContext.client, requestContext.workspace.id, id, input(body))); } catch (error) { return errorResponse(error); } }
