import { NextRequest, NextResponse } from "next/server";
import { isAdminPrivateEmail } from "@/lib/auth/isAdminEmail";
import { getBacklinkOutreachById, updateBacklinkOutreachLifecycleIfStatus } from "@/lib/backlinks/repositories/outreachRepository";
import { BacklinkOutreachLifecycleError, transitionBacklinkOutreachLifecycle, type BacklinkOutreachLifecycleTransition, type BacklinkOutreachResponseType } from "@/lib/backlinks/services/outreachLifecycleService";
import { getRequestUserAndWorkspace } from "@/lib/server/routeAuth";

const responseTypes = new Set<BacklinkOutreachResponseType>(["positive", "negative", "neutral", "bounced", "unsubscribed"]);
function parse(value: unknown): BacklinkOutreachLifecycleTransition | null { if (typeof value !== "object" || value == null || Array.isArray(value)) return null; const body = value as Record<string, unknown>; if (body.confirm !== true || typeof body.action !== "string") return null; const keys = Object.keys(body); if (body.action === "mark_replied" && keys.length === 3 && typeof body.responseType === "string" && responseTypes.has(body.responseType as BacklinkOutreachResponseType)) return { kind: "mark_replied", responseType: body.responseType as BacklinkOutreachResponseType }; if (["open_conversation", "mark_no_response", "pause"].includes(body.action) && keys.length === 2) return { kind: body.action } as BacklinkOutreachLifecycleTransition; if (body.action === "decline" && keys.length === 3 && typeof body.stopReason === "string") return { kind: "decline", stopReason: body.stopReason }; if (body.action === "close" && (keys.length === 3 || keys.length === 4) && typeof body.stopReason === "string" && (body.responseType === undefined || body.responseType === null || typeof body.responseType === "string" && responseTypes.has(body.responseType as BacklinkOutreachResponseType))) return { kind: "close", stopReason: body.stopReason, responseType: body.responseType as BacklinkOutreachResponseType | null | undefined }; return null; }
export async function POST(request: NextRequest, context: { params: Promise<{ id: string }> }) { const auth = await getRequestUserAndWorkspace(request); if (auth.status === "unauthenticated") return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (auth.status === "workspace_forbidden" || !isAdminPrivateEmail(auth.user.email)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const transition = parse(await request.json().catch(() => null)); if (!transition) return NextResponse.json({ error: "Invalid request body" }, { status: 400 }); const { id } = await context.params; try { const result = await transitionBacklinkOutreachLifecycle({ getOutreach: (workspaceId, outreachId) => getBacklinkOutreachById(auth.client, workspaceId, outreachId), updateIfStatus: (workspaceId, outreachId, expectedStatus, patch) => updateBacklinkOutreachLifecycleIfStatus(auth.client, workspaceId, outreachId, expectedStatus, patch) })({ workspaceId: auth.workspace.id, actorUserId: auth.user.id, outreachId: id, transition }); return NextResponse.json({ ok: true, result }); } catch (error) { if (error instanceof BacklinkOutreachLifecycleError) return NextResponse.json({ error: "Outreach lifecycle transition unavailable." }, { status: 409 }); return NextResponse.json({ error: "Outreach lifecycle unavailable." }, { status: 409 }); } }
