"use client";

import Link from "next/link";

export function TermsContent() {
  return (
    <div className="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-20">
      <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-400">
        Terms of Service
      </p>
      <h1 className="mt-3 text-2xl font-semibold tracking-tight text-white sm:text-3xl">
        Terms of Service Norixo
      </h1>
      <div className="mt-8 space-y-4 text-sm leading-7 text-slate-300">
        <p>
          Norixo Optimize is a service for analyzing and helping improve short-term rental listings.
          The recommendations provided are indicative and should be reviewed by the user before making any decision.
        </p>
        <p>
          Access to the service may require a user account. The user is responsible for the accuracy of the information
          submitted and for how they use the results generated by Norixo.
        </p>
        <p>
          The content, reports, interfaces, and brand elements of Norixo remain the property of Norixo or its rights
          holders. Any unauthorized reproduction is prohibited.
        </p>
        <p>
          For any question about the terms of service, you can contact us through the contact page.
        </p>
      </div>
      <p className="mt-10">
        <Link
          href="/"
          className="text-sm font-medium text-slate-400 underline-offset-4 transition-colors hover:text-white hover:underline"
        >
          Back to home
        </Link>
      </p>
    </div>
  );
}
