import { NextRequest, NextResponse } from "next/server";
import { isAdminPrivateEmail } from "@/lib/auth/isAdminEmail";
import { createContact, listContacts, type ContactInput } from "@/lib/backlinks/services/contactService";
import { getRequestUserAndWorkspace } from "@/lib/server/routeAuth";
function isRecord(body: unknown): body is Record<string, unknown> { return typeof body === "object" && body != null && !Array.isArray(body); }
function value(body: Record<string, unknown>, key: string) { const candidate = body[key]; return typeof candidate === "string" ? candidate : undefined; }
function errorResponse(error: unknown) { const code = typeof error === "object" && error != null && "code" in error && typeof error.code === "string" ? error.code : null; const message = error instanceof Error ? error.message : "Impossible de traiter les contacts."; return NextResponse.json({ error: message }, { status: code === "NOT_FOUND" ? 404 : code === "VALIDATION" ? 400 : code === "CONFLICT" ? 409 : code === "FORBIDDEN" ? 403 : 500 }); }
async function context(request: NextRequest) { const result = await getRequestUserAndWorkspace(request); if (result.status === "unauthenticated") return null; if (result.status === "workspace_forbidden") return "forbidden" as const; return isAdminPrivateEmail(result.user.email) ? { client: result.client, user: result.user, workspace: result.workspace } : "forbidden" as const; }
function input(body: Record<string, unknown>): ContactInput | null { const domain_id = value(body, "domain_id"); const contact_key = value(body, "contact_key"); return domain_id && contact_key ? { domain_id, contact_key, ...(value(body, "full_name") !== undefined ? { full_name: value(body, "full_name") } : {}), ...(value(body, "role_title") !== undefined ? { role_title: value(body, "role_title") } : {}), ...(value(body, "email_normalized") !== undefined ? { email_normalized: value(body, "email_normalized") } : {}), ...(value(body, "linkedin_url") !== undefined ? { linkedin_url: value(body, "linkedin_url") } : {}), ...(value(body, "contact_form_url") !== undefined ? { contact_form_url: value(body, "contact_form_url") } : {}), ...(value(body, "contact_status") !== undefined ? { contact_status: value(body, "contact_status") } : {}), ...(value(body, "source_type") !== undefined ? { source_type: value(body, "source_type") } : {}), ...(value(body, "source_reference") !== undefined ? { source_reference: value(body, "source_reference") } : {}), ...(value(body, "consent_or_basis_note") !== undefined ? { consent_or_basis_note: value(body, "consent_or_basis_note") } : {}) } : null; }
export async function GET(request: NextRequest) { const requestContext = await context(request); if (requestContext == null) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (requestContext === "forbidden") return NextResponse.json({ error: "Forbidden" }, { status: 403 }); try { return NextResponse.json(await listContacts(requestContext.client, requestContext.workspace.id)); } catch (error) { return errorResponse(error); } }
export async function POST(request: NextRequest) { const requestContext = await context(request); if (requestContext == null) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (requestContext === "forbidden") return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const body: unknown = await request.json().catch(() => null); if (!isRecord(body)) return NextResponse.json({ error: "Invalid request body" }, { status: 400 }); const requestInput = input(body); if (!requestInput) return NextResponse.json({ error: "Invalid request body" }, { status: 400 }); try { return NextResponse.json(await createContact(requestContext.client, requestContext.workspace.id, requestContext.user.id, requestInput), { status: 201 }); } catch (error) { return errorResponse(error); } }
