import { NextRequest, NextResponse } from "next/server";
import { isAdminPrivateEmail } from "@/lib/auth/isAdminEmail";
import { createBacklinkOutreachDraftRouteServices } from "@/lib/backlinks/services/outreachDraftRouteService";
import { getRequestUserAndWorkspace } from "@/lib/server/routeAuth";
import { createSupabaseAdminClient } from "@/lib/supabase-admin";

const channels = ["email", "linkedin", "contact_form"] as const;
function parse(value: unknown) { if (typeof value !== "object" || value == null || Array.isArray(value)) return null; const record = value as Record<string, unknown>; const keys = Object.keys(record); if (keys.length !== 5 || !["campaignId", "opportunityId", "contactId", "channel", "confirm"].every((key) => keys.includes(key))) return null; return typeof record.campaignId === "string" && typeof record.opportunityId === "string" && typeof record.contactId === "string" && record.confirm === true && channels.includes(record.channel as typeof channels[number]) ? { campaignId: record.campaignId, opportunityId: record.opportunityId, contactId: record.contactId, channel: record.channel as typeof channels[number] } : null; }
export async function POST(request: NextRequest) { const auth = await getRequestUserAndWorkspace(request); if (auth.status === "unauthenticated") return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (auth.status === "workspace_forbidden" || !isAdminPrivateEmail(auth.user.email)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const input = parse(await request.json().catch(() => null)); if (!input) return NextResponse.json({ error: "Invalid request body" }, { status: 400 }); try { const result = await createBacklinkOutreachDraftRouteServices(auth.client, createSupabaseAdminClient()).create({ ...input, workspaceId: auth.workspace.id, actorUserId: auth.user.id }); return NextResponse.json({ ok: true, result }); } catch { return NextResponse.json({ error: "Draft creation unavailable." }, { status: 409 }); } }
