import { BacklinkRepositoryError, normalizeBacklinkRepositoryError } from "./errors";
import type { BacklinkRepositoryClient } from "./repositoryClient";

export type LinkedInInteractionType = "connection_invitation_sent" | "connection_accepted" | "connection_rejected" | "connection_withdrawn" | "connection_expired" | "message_sent" | "reply_confirmed";
export type LinkedInInteraction = { id: string; outreach_id: string; contact_id: string; actor_user_id: string; interaction_type: LinkedInInteractionType; occurred_at: string; target_profile_url: string; source: string; idempotency_key: string; created_at: string };
type RpcClient = { rpc(name: "record_backlink_manual_linkedin_interaction" | "record_backlink_manual_linkedin_message_sent", args: Record<string, unknown>): PromiseLike<{ data: unknown[] | null; error: unknown }> };

function required(value: string, field: string) { const result = value.trim(); if (!result) throw new BacklinkRepositoryError({ code: "VALIDATION", operation: "linkedinInteractions", message: `${field} is required.` }); return result; }
function mapResult(value: unknown) { if (typeof value !== "object" || value == null || Array.isArray(value)) throw new BacklinkRepositoryError({ code: "DATABASE", operation: "linkedinInteractions", message: "Invalid LinkedIn interaction result." }); const row = value as Record<string, unknown>; if ((row.disposition !== "created" && row.disposition !== "existing") || typeof row.interaction_id !== "string" || typeof row.occurred_at !== "string") throw new BacklinkRepositoryError({ code: "DATABASE", operation: "linkedinInteractions", message: "Invalid LinkedIn interaction result." }); return { disposition: row.disposition, interactionId: row.interaction_id, occurredAt: row.occurred_at, attemptId: typeof row.attempt_id === "string" ? row.attempt_id : null }; }
function rpcError(operation: string, error: unknown) { if (typeof error === "object" && error != null && "message" in error && typeof error.message === "string" && error.message.startsWith("LINKEDIN_INTERACTION_")) return new BacklinkRepositoryError({ code: error.message.includes("CONFLICT") || error.message.includes("INCONSISTENT") ? "CONFLICT" : "VALIDATION", operation, message: error.message }); return normalizeBacklinkRepositoryError(operation, error); }
export async function recordLinkedInInteraction(client: RpcClient, input: { workspaceId: string; outreachId: string; actorUserId: string; interactionType: Exclude<LinkedInInteractionType, "message_sent" | "reply_confirmed">; idempotencyKey: string }) { const { data, error } = await client.rpc("record_backlink_manual_linkedin_interaction", { p_workspace_id: required(input.workspaceId, "workspaceId"), p_outreach_id: required(input.outreachId, "outreachId"), p_actor_user_id: required(input.actorUserId, "actorUserId"), p_interaction_type: input.interactionType, p_idempotency_key: required(input.idempotencyKey, "idempotencyKey") }); if (error != null) throw rpcError("recordLinkedInInteraction", error); if (!Array.isArray(data) || data.length !== 1) throw new BacklinkRepositoryError({ code: "DATABASE", operation: "recordLinkedInInteraction", message: "Invalid LinkedIn interaction result." }); return mapResult(data[0]); }
export async function recordLinkedInMessageSent(client: RpcClient, input: { workspaceId: string; outreachId: string; actorUserId: string; idempotencyKey: string }) { const { data, error } = await client.rpc("record_backlink_manual_linkedin_message_sent", { p_workspace_id: required(input.workspaceId, "workspaceId"), p_outreach_id: required(input.outreachId, "outreachId"), p_actor_user_id: required(input.actorUserId, "actorUserId"), p_idempotency_key: required(input.idempotencyKey, "idempotencyKey") }); if (error != null) throw rpcError("recordLinkedInMessageSent", error); if (!Array.isArray(data) || data.length !== 1) throw new BacklinkRepositoryError({ code: "DATABASE", operation: "recordLinkedInMessageSent", message: "Invalid LinkedIn interaction result." }); return mapResult(data[0]); }
export async function listLinkedInInteractions(client: BacklinkRepositoryClient, workspaceId: string, outreachId: string): Promise<LinkedInInteraction[]> { const queryClient = client as unknown as { from(table: string): { select(columns: string): { eq(column: string, value: string): { eq(column: string, value: string): { order(column: string, options: { ascending: boolean }): { order(column: string, options: { ascending: boolean }): { order(column: string, options: { ascending: boolean }): PromiseLike<{ data: unknown[] | null; error: unknown }> } } } } } } }; const { data, error } = await queryClient.from("backlink_linkedin_interactions").select("*").eq("workspace_id", workspaceId).eq("outreach_id", outreachId).order("occurred_at", { ascending: true }).order("created_at", { ascending: true }).order("id", { ascending: true }); if (error != null) throw normalizeBacklinkRepositoryError("listLinkedInInteractions", error); return (data ?? []) as LinkedInInteraction[]; }
