import { BacklinkRepositoryError, normalizeBacklinkRepositoryError } from "./errors";
import type { BacklinkRepositoryClient } from "./repositoryClient";
import type { WorkspaceId } from "./types";
import type { Database } from "@/types/database.types";

export type BacklinkOutreachAttemptRow = Database["public"]["Tables"]["backlink_outreach_attempts"]["Row"];
type BacklinkOutreachAttemptInsert = Database["public"]["Tables"]["backlink_outreach_attempts"]["Insert"];
export type CreateBacklinkOutreachAttemptInput = { outreachId: string; actorUserId: string; channel: string; provider: string; recipient: string; idempotencyKey: string; replyTokenHash: string };
export type BacklinkOutreachAttemptStatePatch = Pick<BacklinkOutreachAttemptInsert, "status" | "provider_message_id" | "error_code" | "error_message" | "accepted_at" | "failed_at" | "resolved_at">;
export type BacklinkOutreachAttemptReservation = { attempt: BacklinkOutreachAttemptRow; disposition: "created" | "existing" };
export type BacklinkOutreachAttemptSummary = { latestStatus: BacklinkOutreachAttemptRow["status"] | null; hasOpenAttempt: boolean };

function required(value: string, field: string): string { const normalized = value.trim(); if (!normalized) throw new BacklinkRepositoryError({ code: "VALIDATION", operation: "createBacklinkOutreachAttempt", message: `${field} is required.` }); return normalized; }
export async function getBacklinkOutreachAttemptById(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, attemptId: string): Promise<BacklinkOutreachAttemptRow> { const { data, error } = await client.from("backlink_outreach_attempts").select("*").eq("workspace_id", workspaceId).eq("id", attemptId).maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("getBacklinkOutreachAttemptById", error); if (data == null) throw new BacklinkRepositoryError({ code: "NOT_FOUND", operation: "getBacklinkOutreachAttemptById", message: "The requested record was not found." }); return data; }
export async function getBacklinkOutreachAttemptByIdempotencyKey(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, idempotencyKey: string): Promise<BacklinkOutreachAttemptRow | null> { const { data, error } = await client.from("backlink_outreach_attempts").select("*").eq("workspace_id", workspaceId).eq("idempotency_key", idempotencyKey.trim()).maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("getBacklinkOutreachAttemptByIdempotencyKey", error); return data; }
export async function getBacklinkOutreachAttemptByProviderMessageId(client: BacklinkRepositoryClient, provider: string, providerMessageId: string): Promise<BacklinkOutreachAttemptRow | null> { const normalizedProvider = provider.trim(); const normalizedProviderMessageId = providerMessageId.trim(); if (normalizedProvider !== "resend" || !normalizedProviderMessageId) throw new BacklinkRepositoryError({ code: "VALIDATION", operation: "getBacklinkOutreachAttemptByProviderMessageId", message: "The provided data is invalid." }); const { data, error } = await client.from("backlink_outreach_attempts").select("*").eq("provider", normalizedProvider).eq("provider_message_id", normalizedProviderMessageId).maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("getBacklinkOutreachAttemptByProviderMessageId", error); return data; }
export async function getBacklinkOutreachAttemptByReplyTokenHash(client: BacklinkRepositoryClient, replyTokenHash: string): Promise<BacklinkOutreachAttemptRow | null> { const normalizedReplyTokenHash = replyTokenHash.trim(); if (!/^[0-9a-f]{64}$/i.test(normalizedReplyTokenHash)) throw new BacklinkRepositoryError({ code: "VALIDATION", operation: "getBacklinkOutreachAttemptByReplyTokenHash", message: "The provided data is invalid." }); const { data, error } = await client.from("backlink_outreach_attempts").select("*").eq("reply_token_hash", normalizedReplyTokenHash.toLowerCase()).maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("getBacklinkOutreachAttemptByReplyTokenHash", error); return data; }
export async function listBacklinkOutreachAttemptsForOutreach(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, outreachId: string): Promise<BacklinkOutreachAttemptRow[]> { const { data, error } = await client.from("backlink_outreach_attempts").select("*").eq("workspace_id", workspaceId).eq("outreach_id", outreachId).order("requested_at", { ascending: false }); if (error != null) throw normalizeBacklinkRepositoryError("listBacklinkOutreachAttemptsForOutreach", error); return data ?? []; }
export async function listBacklinkOutreachAttemptSummariesForOutreachIds(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, outreachIds: readonly string[]): Promise<Map<string, BacklinkOutreachAttemptSummary>> { if (outreachIds.length === 0) return new Map(); const { data, error } = await client.from("backlink_outreach_attempts").select("outreach_id,status,requested_at").eq("workspace_id", workspaceId).in("outreach_id", outreachIds).order("requested_at", { ascending: false }); if (error != null) throw normalizeBacklinkRepositoryError("listBacklinkOutreachAttemptSummariesForOutreachIds", error); const summaries = new Map<string, BacklinkOutreachAttemptSummary>(); for (const attempt of data ?? []) { const current = summaries.get(attempt.outreach_id); summaries.set(attempt.outreach_id, { latestStatus: current?.latestStatus ?? attempt.status, hasOpenAttempt: Boolean(current?.hasOpenAttempt || attempt.status === "requested" || attempt.status === "unknown") }); } return summaries; }
export async function getOpenBacklinkOutreachAttemptForOutreach(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, outreachId: string): Promise<BacklinkOutreachAttemptRow | null> { const { data, error } = await client.from("backlink_outreach_attempts").select("*").eq("workspace_id", workspaceId).eq("outreach_id", outreachId).in("status", ["requested", "unknown"]).order("requested_at", { ascending: false }).maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("getOpenBacklinkOutreachAttemptForOutreach", error); return data; }
export async function createBacklinkOutreachAttempt(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, input: CreateBacklinkOutreachAttemptInput): Promise<BacklinkOutreachAttemptRow> { const idempotencyKey = required(input.idempotencyKey, "idempotencyKey"); const payload: BacklinkOutreachAttemptInsert = { workspace_id: workspaceId, outreach_id: input.outreachId, actor_user_id: input.actorUserId, channel: input.channel, provider: required(input.provider, "provider"), recipient: required(input.recipient, "recipient"), idempotency_key: idempotencyKey, reply_token_hash: required(input.replyTokenHash, "replyTokenHash"), status: "requested" }; const { data, error } = await client.from("backlink_outreach_attempts").insert(payload).select("*").single(); if (error == null) return data; const normalized = normalizeBacklinkRepositoryError("createBacklinkOutreachAttempt", error); if (normalized.code !== "CONFLICT") throw normalized; const existing = await getBacklinkOutreachAttemptByIdempotencyKey(client, workspaceId, idempotencyKey); if (existing != null) return existing; throw normalized; }
export async function reserveBacklinkOutreachAttempt(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, input: CreateBacklinkOutreachAttemptInput): Promise<BacklinkOutreachAttemptReservation> { const idempotencyKey = required(input.idempotencyKey, "idempotencyKey"); const payload: BacklinkOutreachAttemptInsert = { workspace_id: workspaceId, outreach_id: input.outreachId, actor_user_id: input.actorUserId, channel: input.channel, provider: required(input.provider, "provider"), recipient: required(input.recipient, "recipient"), idempotency_key: idempotencyKey, reply_token_hash: required(input.replyTokenHash, "replyTokenHash"), status: "requested" }; const { data, error } = await client.from("backlink_outreach_attempts").insert(payload).select("*").single(); if (error == null) return { attempt: data, disposition: "created" }; const normalized = normalizeBacklinkRepositoryError("reserveBacklinkOutreachAttempt", error); if (normalized.code !== "CONFLICT") throw normalized; const existing = await getBacklinkOutreachAttemptByIdempotencyKey(client, workspaceId, idempotencyKey); if (existing != null) return { attempt: existing, disposition: "existing" }; throw normalized; }
export async function updateBacklinkOutreachAttemptState(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, attemptId: string, patch: BacklinkOutreachAttemptStatePatch): Promise<BacklinkOutreachAttemptRow> { const { data, error } = await client.from("backlink_outreach_attempts").update(patch).eq("workspace_id", workspaceId).eq("id", attemptId).select("*").maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("updateBacklinkOutreachAttemptState", error); if (data == null) throw new BacklinkRepositoryError({ code: "NOT_FOUND", operation: "updateBacklinkOutreachAttemptState", message: "The requested record was not found." }); return data; }
export async function resolveUnknownBacklinkOutreachAttemptState(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, attemptId: string, patch: BacklinkOutreachAttemptStatePatch): Promise<BacklinkOutreachAttemptRow | null> { const { data, error } = await client.from("backlink_outreach_attempts").update(patch).eq("workspace_id", workspaceId).eq("id", attemptId).eq("status", "unknown").select("*").maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("resolveUnknownBacklinkOutreachAttemptState", error); return data; }
