import { BacklinkRepositoryError, normalizeBacklinkRepositoryError } from "./errors";
import type { BacklinkRepositoryClient } from "./repositoryClient";
import type { WorkspaceId } from "./types";
import type { Database } from "@/types/database.types";

export type BacklinkOutreachAttemptRow = Database["public"]["Tables"]["backlink_outreach_attempts"]["Row"];
type BacklinkOutreachAttemptInsert = Database["public"]["Tables"]["backlink_outreach_attempts"]["Insert"];
type ReserveBacklinkOutreachFollowUpAttemptRpcName = "reserve_backlink_outreach_follow_up_attempt";
type ReserveBacklinkOutreachFollowUpAttemptRpcArgs = Database["public"]["Functions"][ReserveBacklinkOutreachFollowUpAttemptRpcName]["Args"];
type ReserveBacklinkOutreachFollowUpAttemptRpcRow = Database["public"]["Functions"][ReserveBacklinkOutreachFollowUpAttemptRpcName]["Returns"][number];
type CancelBacklinkOutreachPreparedFollowUpAttemptRpcName = "cancel_backlink_outreach_prepared_follow_up_attempt";
type CancelBacklinkOutreachPreparedFollowUpAttemptRpcArgs = Database["public"]["Functions"][CancelBacklinkOutreachPreparedFollowUpAttemptRpcName]["Args"];
type CancelBacklinkOutreachPreparedFollowUpAttemptRpcRow = Database["public"]["Functions"][CancelBacklinkOutreachPreparedFollowUpAttemptRpcName]["Returns"][number];
type ApplyBacklinkOutreachFollowUpAcceptedRpcName = "apply_backlink_outreach_follow_up_accepted";
type ApplyBacklinkOutreachFollowUpAcceptedRpcArgs = Database["public"]["Functions"][ApplyBacklinkOutreachFollowUpAcceptedRpcName]["Args"];
type ApplyBacklinkOutreachFollowUpAcceptedRpcRow = Database["public"]["Functions"][ApplyBacklinkOutreachFollowUpAcceptedRpcName]["Returns"][number];
type MarkBacklinkOutreachFollowUpAttemptRequestedRpcName = "mark_backlink_outreach_follow_up_attempt_requested";
type MarkBacklinkOutreachFollowUpAttemptRequestedRpcArgs = Database["public"]["Functions"][MarkBacklinkOutreachFollowUpAttemptRequestedRpcName]["Args"];
type MarkBacklinkOutreachFollowUpAttemptRequestedRpcRow = Database["public"]["Functions"][MarkBacklinkOutreachFollowUpAttemptRequestedRpcName]["Returns"][number];
export type BacklinkOutreachAttemptKind = "initial" | "follow_up";
export type CreateBacklinkOutreachAttemptInput = { attemptId: string; outreachId: string; actorUserId: string; channel: string; provider: string; recipient: string; idempotencyKey: string; replyTokenHash: string; replyTokenKeyVersion: string; attemptKind: BacklinkOutreachAttemptKind };
export type BacklinkOutreachAttemptStatePatch = Pick<BacklinkOutreachAttemptInsert, "status" | "provider_message_id" | "error_code" | "error_message" | "accepted_at" | "failed_at" | "resolved_at">;
export type BacklinkOutreachAttemptReservation = { attempt: BacklinkOutreachAttemptRow; disposition: "created" | "existing" };
export type BacklinkOutreachAttemptSummary = { latestStatus: BacklinkOutreachAttemptRow["status"] | null; hasOpenAttempt: boolean };
export type ReserveBacklinkOutreachFollowUpAttemptInput = { workspaceId: string; outreachId: string; attemptId: string; actorUserId: string; idempotencyKey: string; replyTokenHash: string; replyTokenKeyVersion: string; reservedAt: string };
export type ReserveBacklinkOutreachFollowUpAttemptResult = { disposition: "reserved" | "existing"; attemptId: string; outreachId: string; attemptStatus: "prepared" | "cancelled"; attemptKind: "follow_up"; preparedAt: string | null; requestedAt: string | null };
export type CancelBacklinkOutreachPreparedFollowUpAttemptInput = { workspaceId: string; outreachId: string; attemptId: string; cancelReason: "inbound_reply" | "provider_complaint" | "provider_permanent_bounce" | "contact_unavailable" | "admin_cancelled"; cancelledAt: string };
export type CancelBacklinkOutreachPreparedFollowUpAttemptResult = { disposition: "cancelled" | "existing"; attemptId: string; outreachId: string; attemptStatus: "cancelled"; cancelReason: CancelBacklinkOutreachPreparedFollowUpAttemptInput["cancelReason"]; cancelledAt: string };
export type ApplyBacklinkOutreachFollowUpAcceptedInput = { workspaceId: string; outreachId: string; attemptId: string; providerMessageId: string | null; acceptedAt: string };
export type ApplyBacklinkOutreachFollowUpAcceptedResult = { disposition: "applied" | "existing"; attemptStatus: "accepted"; outreachStatus: string; currentAttempt: number; lastAttemptAt: string | null };
export type MarkBacklinkOutreachFollowUpAttemptRequestedInput = { workspaceId: string; outreachId: string; attemptId: string; actorUserId: string; requestedAt: string };
export type MarkBacklinkOutreachFollowUpAttemptRequestedResult = { disposition: "requested_now" | "existing"; attemptId: string; outreachId: string; recipient: string; subject: string; body: string; replyTokenHash: string; replyTokenKeyVersion: string; requestedAt: string };
export type ReserveBacklinkOutreachFollowUpAttemptRpcClient = { rpc(functionName: ReserveBacklinkOutreachFollowUpAttemptRpcName, args: ReserveBacklinkOutreachFollowUpAttemptRpcArgs): PromiseLike<{ data: ReserveBacklinkOutreachFollowUpAttemptRpcRow[] | null; error: unknown }> };
export type CancelBacklinkOutreachPreparedFollowUpAttemptRpcClient = { rpc(functionName: CancelBacklinkOutreachPreparedFollowUpAttemptRpcName, args: CancelBacklinkOutreachPreparedFollowUpAttemptRpcArgs): PromiseLike<{ data: CancelBacklinkOutreachPreparedFollowUpAttemptRpcRow[] | null; error: unknown }> };
export type ApplyBacklinkOutreachFollowUpAcceptedRpcClient = { rpc(functionName: ApplyBacklinkOutreachFollowUpAcceptedRpcName, args: ApplyBacklinkOutreachFollowUpAcceptedRpcArgs): PromiseLike<{ data: ApplyBacklinkOutreachFollowUpAcceptedRpcRow[] | null; error: unknown }> };
export type MarkBacklinkOutreachFollowUpAttemptRequestedRpcClient = { rpc(functionName: MarkBacklinkOutreachFollowUpAttemptRequestedRpcName, args: MarkBacklinkOutreachFollowUpAttemptRequestedRpcArgs): PromiseLike<{ data: MarkBacklinkOutreachFollowUpAttemptRequestedRpcRow[] | null; error: unknown }> };

function required(value: string, field: string): string { const normalized = value.trim(); if (!normalized) throw new BacklinkRepositoryError({ code: "VALIDATION", operation: "createBacklinkOutreachAttempt", message: `${field} is required.` }); return normalized; }
export async function getBacklinkOutreachAttemptById(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, attemptId: string): Promise<BacklinkOutreachAttemptRow> { const { data, error } = await client.from("backlink_outreach_attempts").select("*").eq("workspace_id", workspaceId).eq("id", attemptId).maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("getBacklinkOutreachAttemptById", error); if (data == null) throw new BacklinkRepositoryError({ code: "NOT_FOUND", operation: "getBacklinkOutreachAttemptById", message: "The requested record was not found." }); return data; }
export async function getBacklinkOutreachAttemptByIdempotencyKey(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, idempotencyKey: string): Promise<BacklinkOutreachAttemptRow | null> { const { data, error } = await client.from("backlink_outreach_attempts").select("*").eq("workspace_id", workspaceId).eq("idempotency_key", idempotencyKey.trim()).maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("getBacklinkOutreachAttemptByIdempotencyKey", error); return data; }
export async function getBacklinkOutreachAttemptByProviderMessageId(client: BacklinkRepositoryClient, provider: string, providerMessageId: string): Promise<BacklinkOutreachAttemptRow | null> { const normalizedProvider = provider.trim(); const normalizedProviderMessageId = providerMessageId.trim(); if (normalizedProvider !== "resend" || !normalizedProviderMessageId) throw new BacklinkRepositoryError({ code: "VALIDATION", operation: "getBacklinkOutreachAttemptByProviderMessageId", message: "The provided data is invalid." }); const { data, error } = await client.from("backlink_outreach_attempts").select("*").eq("provider", normalizedProvider).eq("provider_message_id", normalizedProviderMessageId).maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("getBacklinkOutreachAttemptByProviderMessageId", error); return data; }
export async function getBacklinkOutreachAttemptByReplyTokenHash(client: BacklinkRepositoryClient, replyTokenHash: string): Promise<BacklinkOutreachAttemptRow | null> { const normalizedReplyTokenHash = replyTokenHash.trim(); if (!/^[0-9a-f]{64}$/i.test(normalizedReplyTokenHash)) throw new BacklinkRepositoryError({ code: "VALIDATION", operation: "getBacklinkOutreachAttemptByReplyTokenHash", message: "The provided data is invalid." }); const { data, error } = await client.from("backlink_outreach_attempts").select("*").eq("reply_token_hash", normalizedReplyTokenHash.toLowerCase()).maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("getBacklinkOutreachAttemptByReplyTokenHash", error); return data; }
export async function listBacklinkOutreachAttemptsForOutreach(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, outreachId: string): Promise<BacklinkOutreachAttemptRow[]> { const { data, error } = await client.from("backlink_outreach_attempts").select("*").eq("workspace_id", workspaceId).eq("outreach_id", outreachId).order("requested_at", { ascending: false }); if (error != null) throw normalizeBacklinkRepositoryError("listBacklinkOutreachAttemptsForOutreach", error); return data ?? []; }
export async function listBacklinkOutreachAttemptSummariesForOutreachIds(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, outreachIds: readonly string[]): Promise<Map<string, BacklinkOutreachAttemptSummary>> { if (outreachIds.length === 0) return new Map(); const { data, error } = await client.from("backlink_outreach_attempts").select("outreach_id,status,requested_at,prepared_at").eq("workspace_id", workspaceId).in("outreach_id", outreachIds).order("created_at", { ascending: false }); if (error != null) throw normalizeBacklinkRepositoryError("listBacklinkOutreachAttemptSummariesForOutreachIds", error); const summaries = new Map<string, BacklinkOutreachAttemptSummary>(); for (const attempt of data ?? []) { const current = summaries.get(attempt.outreach_id); summaries.set(attempt.outreach_id, { latestStatus: current?.latestStatus ?? attempt.status, hasOpenAttempt: Boolean(current?.hasOpenAttempt || attempt.status === "prepared" || attempt.status === "requested" || attempt.status === "unknown") }); } return summaries; }
export async function getOpenBacklinkOutreachAttemptForOutreach(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, outreachId: string): Promise<BacklinkOutreachAttemptRow | null> { const { data, error } = await client.from("backlink_outreach_attempts").select("*").eq("workspace_id", workspaceId).eq("outreach_id", outreachId).in("status", ["prepared", "requested", "unknown"]).order("created_at", { ascending: false }).maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("getOpenBacklinkOutreachAttemptForOutreach", error); return data; }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function mapFollowUpReservation(value: unknown): ReserveBacklinkOutreachFollowUpAttemptResult { if (!isRecord(value)) throw new BacklinkRepositoryError({ code: "DATABASE", operation: "reserveBacklinkOutreachFollowUpAttempt", message: "The database returned an invalid follow-up reservation." }); const { disposition, attempt_id: attemptId, outreach_id: outreachId, attempt_status: attemptStatus, attempt_kind: attemptKind, prepared_at: preparedAt, requested_at: requestedAt } = value; if ((disposition !== "reserved" && disposition !== "existing") || typeof attemptId !== "string" || typeof outreachId !== "string" || (attemptStatus !== "prepared" && attemptStatus !== "cancelled") || attemptKind !== "follow_up" || (typeof preparedAt !== "string" && preparedAt !== null) || (typeof requestedAt !== "string" && requestedAt !== null)) throw new BacklinkRepositoryError({ code: "DATABASE", operation: "reserveBacklinkOutreachFollowUpAttempt", message: "The database returned an invalid follow-up reservation." }); return { disposition, attemptId, outreachId, attemptStatus, attemptKind, preparedAt, requestedAt }; }
function normalizeFollowUpReservationError(error: unknown): BacklinkRepositoryError { if (typeof error === "object" && error != null && "message" in error && typeof error.message === "string" && error.message.startsWith("FOLLOW_UP_")) { const code = error.message === "FOLLOW_UP_IDEMPOTENCY_CONFLICT" ? "CONFLICT" : "VALIDATION"; return new BacklinkRepositoryError({ code, operation: "reserveBacklinkOutreachFollowUpAttempt", message: error.message }); } return normalizeBacklinkRepositoryError("reserveBacklinkOutreachFollowUpAttempt", error); }
export async function reserveBacklinkOutreachFollowUpAttempt(client: ReserveBacklinkOutreachFollowUpAttemptRpcClient, input: ReserveBacklinkOutreachFollowUpAttemptInput): Promise<ReserveBacklinkOutreachFollowUpAttemptResult> { const { data, error } = await client.rpc("reserve_backlink_outreach_follow_up_attempt", { p_workspace_id: required(input.workspaceId, "workspaceId"), p_outreach_id: required(input.outreachId, "outreachId"), p_attempt_id: required(input.attemptId, "attemptId"), p_actor_user_id: required(input.actorUserId, "actorUserId"), p_idempotency_key: required(input.idempotencyKey, "idempotencyKey"), p_reply_token_hash: required(input.replyTokenHash, "replyTokenHash"), p_reply_token_key_version: required(input.replyTokenKeyVersion, "replyTokenKeyVersion"), p_reserved_at: required(input.reservedAt, "reservedAt") }); if (error != null) throw normalizeFollowUpReservationError(error); if (!Array.isArray(data) || data.length !== 1) throw new BacklinkRepositoryError({ code: "DATABASE", operation: "reserveBacklinkOutreachFollowUpAttempt", message: "The database returned an invalid follow-up reservation." }); return mapFollowUpReservation(data[0]); }
function mapFollowUpAccepted(value: unknown): ApplyBacklinkOutreachFollowUpAcceptedResult { if (!isRecord(value)) throw new BacklinkRepositoryError({ code: "DATABASE", operation: "applyBacklinkOutreachFollowUpAccepted", message: "The database returned an invalid follow-up accepted result." }); const { disposition, attempt_status: attemptStatus, outreach_status: outreachStatus, current_attempt: currentAttempt, last_attempt_at: lastAttemptAt } = value; if ((disposition !== "applied" && disposition !== "existing") || attemptStatus !== "accepted" || typeof outreachStatus !== "string" || typeof currentAttempt !== "number" || (typeof lastAttemptAt !== "string" && lastAttemptAt !== null)) throw new BacklinkRepositoryError({ code: "DATABASE", operation: "applyBacklinkOutreachFollowUpAccepted", message: "The database returned an invalid follow-up accepted result." }); return { disposition, attemptStatus, outreachStatus, currentAttempt, lastAttemptAt }; }
function normalizeFollowUpAcceptedError(error: unknown): BacklinkRepositoryError { if (typeof error === "object" && error != null && "message" in error && typeof error.message === "string" && error.message.startsWith("FOLLOW_UP_ACCEPTED_")) return new BacklinkRepositoryError({ code: error.message.includes("CONFLICT") ? "CONFLICT" : "VALIDATION", operation: "applyBacklinkOutreachFollowUpAccepted", message: error.message }); return normalizeBacklinkRepositoryError("applyBacklinkOutreachFollowUpAccepted", error); }
export async function applyBacklinkOutreachFollowUpAccepted(client: ApplyBacklinkOutreachFollowUpAcceptedRpcClient, input: ApplyBacklinkOutreachFollowUpAcceptedInput): Promise<ApplyBacklinkOutreachFollowUpAcceptedResult> { const { data, error } = await client.rpc("apply_backlink_outreach_follow_up_accepted", { p_workspace_id: required(input.workspaceId, "workspaceId"), p_outreach_id: required(input.outreachId, "outreachId"), p_attempt_id: required(input.attemptId, "attemptId"), p_provider_message_id: input.providerMessageId, p_accepted_at: required(input.acceptedAt, "acceptedAt") }); if (error != null) throw normalizeFollowUpAcceptedError(error); if (!Array.isArray(data) || data.length !== 1) throw new BacklinkRepositoryError({ code: "DATABASE", operation: "applyBacklinkOutreachFollowUpAccepted", message: "The database returned an invalid follow-up accepted result." }); return mapFollowUpAccepted(data[0]); }
function mapFollowUpRequested(value: unknown): MarkBacklinkOutreachFollowUpAttemptRequestedResult { if (!isRecord(value)) throw new BacklinkRepositoryError({ code: "DATABASE", operation: "markBacklinkOutreachFollowUpAttemptRequested", message: "The database returned an invalid follow-up pre-send result." }); const { disposition, attempt_id: attemptId, outreach_id: outreachId, recipient, subject, body, reply_token_hash: replyTokenHash, reply_token_key_version: replyTokenKeyVersion, requested_at: requestedAt } = value; if ((disposition !== "requested_now" && disposition !== "existing") || typeof attemptId !== "string" || typeof outreachId !== "string" || typeof recipient !== "string" || typeof subject !== "string" || typeof body !== "string" || typeof replyTokenHash !== "string" || typeof replyTokenKeyVersion !== "string" || typeof requestedAt !== "string") throw new BacklinkRepositoryError({ code: "DATABASE", operation: "markBacklinkOutreachFollowUpAttemptRequested", message: "The database returned an invalid follow-up pre-send result." }); return { disposition, attemptId, outreachId, recipient, subject, body, replyTokenHash, replyTokenKeyVersion, requestedAt }; }
function normalizeFollowUpRequestedError(error: unknown): BacklinkRepositoryError { if (typeof error === "object" && error != null && "message" in error && typeof error.message === "string" && error.message.startsWith("FOLLOW_UP_SEND_")) return new BacklinkRepositoryError({ code: error.message.includes("CONFLICT") ? "CONFLICT" : "VALIDATION", operation: "markBacklinkOutreachFollowUpAttemptRequested", message: error.message }); return normalizeBacklinkRepositoryError("markBacklinkOutreachFollowUpAttemptRequested", error); }
export async function markBacklinkOutreachFollowUpAttemptRequested(client: MarkBacklinkOutreachFollowUpAttemptRequestedRpcClient, input: MarkBacklinkOutreachFollowUpAttemptRequestedInput): Promise<MarkBacklinkOutreachFollowUpAttemptRequestedResult> { const { data, error } = await client.rpc("mark_backlink_outreach_follow_up_attempt_requested", { p_workspace_id: required(input.workspaceId, "workspaceId"), p_outreach_id: required(input.outreachId, "outreachId"), p_attempt_id: required(input.attemptId, "attemptId"), p_actor_user_id: required(input.actorUserId, "actorUserId"), p_requested_at: required(input.requestedAt, "requestedAt") }); if (error != null) throw normalizeFollowUpRequestedError(error); if (!Array.isArray(data) || data.length !== 1) throw new BacklinkRepositoryError({ code: "DATABASE", operation: "markBacklinkOutreachFollowUpAttemptRequested", message: "The database returned an invalid follow-up pre-send result." }); return mapFollowUpRequested(data[0]); }
function mapFollowUpCancellation(value: unknown): CancelBacklinkOutreachPreparedFollowUpAttemptResult { if (!isRecord(value)) throw new BacklinkRepositoryError({ code: "DATABASE", operation: "cancelBacklinkOutreachPreparedFollowUpAttempt", message: "The database returned an invalid follow-up cancellation." }); const { disposition, attempt_id: attemptId, outreach_id: outreachId, attempt_status: attemptStatus, cancel_reason: cancelReason, cancelled_at: cancelledAt } = value; if ((disposition !== "cancelled" && disposition !== "existing") || typeof attemptId !== "string" || typeof outreachId !== "string" || attemptStatus !== "cancelled" || (cancelReason !== "inbound_reply" && cancelReason !== "provider_complaint" && cancelReason !== "provider_permanent_bounce" && cancelReason !== "contact_unavailable" && cancelReason !== "admin_cancelled") || typeof cancelledAt !== "string") throw new BacklinkRepositoryError({ code: "DATABASE", operation: "cancelBacklinkOutreachPreparedFollowUpAttempt", message: "The database returned an invalid follow-up cancellation." }); return { disposition, attemptId, outreachId, attemptStatus, cancelReason, cancelledAt }; }
export async function cancelBacklinkOutreachPreparedFollowUpAttempt(client: CancelBacklinkOutreachPreparedFollowUpAttemptRpcClient, input: CancelBacklinkOutreachPreparedFollowUpAttemptInput): Promise<CancelBacklinkOutreachPreparedFollowUpAttemptResult> { const { data, error } = await client.rpc("cancel_backlink_outreach_prepared_follow_up_attempt", { p_workspace_id: required(input.workspaceId, "workspaceId"), p_outreach_id: required(input.outreachId, "outreachId"), p_attempt_id: required(input.attemptId, "attemptId"), p_cancel_reason: input.cancelReason, p_cancelled_at: required(input.cancelledAt, "cancelledAt") }); if (error != null) throw normalizeFollowUpReservationError(error); if (!Array.isArray(data) || data.length !== 1) throw new BacklinkRepositoryError({ code: "DATABASE", operation: "cancelBacklinkOutreachPreparedFollowUpAttempt", message: "The database returned an invalid follow-up cancellation." }); return mapFollowUpCancellation(data[0]); }
export async function createBacklinkOutreachAttempt(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, input: CreateBacklinkOutreachAttemptInput): Promise<BacklinkOutreachAttemptRow> { const idempotencyKey = required(input.idempotencyKey, "idempotencyKey"); const payload: BacklinkOutreachAttemptInsert = { id: required(input.attemptId, "attemptId"), workspace_id: workspaceId, outreach_id: input.outreachId, actor_user_id: input.actorUserId, channel: input.channel, provider: required(input.provider, "provider"), recipient: required(input.recipient, "recipient"), idempotency_key: idempotencyKey, reply_token_hash: required(input.replyTokenHash, "replyTokenHash"), reply_token_key_version: required(input.replyTokenKeyVersion, "replyTokenKeyVersion"), attempt_kind: input.attemptKind, status: "requested" }; const { data, error } = await client.from("backlink_outreach_attempts").insert(payload).select("*").single(); if (error == null) return data; const normalized = normalizeBacklinkRepositoryError("createBacklinkOutreachAttempt", error); if (normalized.code !== "CONFLICT") throw normalized; const existing = await getBacklinkOutreachAttemptByIdempotencyKey(client, workspaceId, idempotencyKey); if (existing != null) return existing; throw normalized; }
export async function reserveBacklinkOutreachAttempt(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, input: CreateBacklinkOutreachAttemptInput): Promise<BacklinkOutreachAttemptReservation> { const idempotencyKey = required(input.idempotencyKey, "idempotencyKey"); const payload: BacklinkOutreachAttemptInsert = { id: required(input.attemptId, "attemptId"), workspace_id: workspaceId, outreach_id: input.outreachId, actor_user_id: input.actorUserId, channel: input.channel, provider: required(input.provider, "provider"), recipient: required(input.recipient, "recipient"), idempotency_key: idempotencyKey, reply_token_hash: required(input.replyTokenHash, "replyTokenHash"), reply_token_key_version: required(input.replyTokenKeyVersion, "replyTokenKeyVersion"), attempt_kind: input.attemptKind, status: "requested" }; const { data, error } = await client.from("backlink_outreach_attempts").insert(payload).select("*").single(); if (error == null) return { attempt: data, disposition: "created" }; const normalized = normalizeBacklinkRepositoryError("reserveBacklinkOutreachAttempt", error); if (normalized.code !== "CONFLICT") throw normalized; const existing = await getBacklinkOutreachAttemptByIdempotencyKey(client, workspaceId, idempotencyKey); if (existing != null) return { attempt: existing, disposition: "existing" }; throw normalized; }
export async function updateBacklinkOutreachAttemptState(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, attemptId: string, patch: BacklinkOutreachAttemptStatePatch): Promise<BacklinkOutreachAttemptRow> { const { data, error } = await client.from("backlink_outreach_attempts").update(patch).eq("workspace_id", workspaceId).eq("id", attemptId).select("*").maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("updateBacklinkOutreachAttemptState", error); if (data == null) throw new BacklinkRepositoryError({ code: "NOT_FOUND", operation: "updateBacklinkOutreachAttemptState", message: "The requested record was not found." }); return data; }
export async function resolveUnknownBacklinkOutreachAttemptState(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, attemptId: string, patch: BacklinkOutreachAttemptStatePatch): Promise<BacklinkOutreachAttemptRow | null> { const { data, error } = await client.from("backlink_outreach_attempts").update(patch).eq("workspace_id", workspaceId).eq("id", attemptId).eq("status", "unknown").select("*").maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("resolveUnknownBacklinkOutreachAttemptState", error); return data; }
export async function recoverRequestedBacklinkOutreachAttemptAsUnknown(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, attemptId: string, patch: BacklinkOutreachAttemptStatePatch): Promise<BacklinkOutreachAttemptRow | null> { const { data, error } = await client.from("backlink_outreach_attempts").update(patch).eq("workspace_id", workspaceId).eq("id", attemptId).eq("status", "requested").select("*").maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("recoverRequestedBacklinkOutreachAttemptAsUnknown", error); return data; }
