import type { Database } from "@/types/database.types";
import { BacklinkRepositoryError, normalizeBacklinkRepositoryError } from "./errors";
import type { BacklinkRepositoryClient } from "./repositoryClient";

export type BacklinkOutreachFollowUpDraftRow = Database["public"]["Tables"]["backlink_outreach_follow_up_drafts"]["Row"];
type PrepareName = "prepare_backlink_outreach_follow_up_draft";
type UpdateName = "update_backlink_outreach_follow_up_draft";
type PrepareArgs = Database["public"]["Functions"][PrepareName]["Args"];
type UpdateArgs = Database["public"]["Functions"][UpdateName]["Args"];
type PrepareRow = Database["public"]["Functions"][PrepareName]["Returns"][number];
type UpdateRow = Database["public"]["Functions"][UpdateName]["Returns"][number];
export type PrepareBacklinkOutreachFollowUpDraftInput = { workspaceId: string; outreachId: string; attemptId: string; actorUserId: string; subject: string; body: string; preparedAt: string };
export type UpdateBacklinkOutreachFollowUpDraftInput = { workspaceId: string; outreachId: string; attemptId: string; actorUserId: string; subject: string; body: string; expectedUpdatedAt: string; updatedAt: string };
export type BacklinkOutreachFollowUpDraftProjection = { id: string; outreachId: string; attemptId: string; followUpNumber: number; subject: string; body: string; preparedAt: string; updatedAt: string; updatedBy: string };
export type PrepareBacklinkOutreachFollowUpDraftResult = BacklinkOutreachFollowUpDraftProjection & { disposition: "created" | "existing" };
function required(value: string) { const result = value.trim(); if (!result) throw new BacklinkRepositoryError({ code: "VALIDATION", operation: "followUpDraft", message: "Required value is missing." }); return result; }
function record(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function map(value: unknown, disposition?: "created" | "existing"): BacklinkOutreachFollowUpDraftProjection & { disposition?: "created" | "existing" } { if (!record(value)) throw new BacklinkRepositoryError({ code: "DATABASE", operation: "followUpDraft", message: "Invalid follow-up draft result." }); const { draft_id: id, outreach_id: outreachId, attempt_id: attemptId, follow_up_number: followUpNumber, subject, body, prepared_at: preparedAt, updated_at: updatedAt, updated_by: updatedBy } = value; if (typeof id !== "string" || typeof outreachId !== "string" || typeof attemptId !== "string" || typeof followUpNumber !== "number" || typeof subject !== "string" || typeof body !== "string" || typeof preparedAt !== "string" || typeof updatedAt !== "string" || typeof updatedBy !== "string") throw new BacklinkRepositoryError({ code: "DATABASE", operation: "followUpDraft", message: "Invalid follow-up draft result." }); return { id, outreachId, attemptId, followUpNumber, subject, body, preparedAt, updatedAt, updatedBy, ...(disposition == null ? {} : { disposition }) }; }
function normalize(error: unknown) { if (record(error) && typeof error.message === "string" && error.message.startsWith("FOLLOW_UP_DRAFT_")) return new BacklinkRepositoryError({ code: error.message === "FOLLOW_UP_DRAFT_CONFLICT" ? "CONFLICT" : "VALIDATION", operation: "followUpDraft", message: error.message }); return normalizeBacklinkRepositoryError("followUpDraft", error); }
export async function getBacklinkOutreachFollowUpDraftByAttemptId(client: BacklinkRepositoryClient, workspaceId: string, attemptId: string): Promise<BacklinkOutreachFollowUpDraftRow | null> { const { data, error } = await client.from("backlink_outreach_follow_up_drafts").select("*").eq("workspace_id", workspaceId).eq("attempt_id", attemptId).maybeSingle(); if (error != null) throw normalize(error); return data; }
export async function prepareBacklinkOutreachFollowUpDraft(client: { rpc(name: PrepareName, args: PrepareArgs): PromiseLike<{ data: PrepareRow[] | null; error: unknown }> }, input: PrepareBacklinkOutreachFollowUpDraftInput): Promise<PrepareBacklinkOutreachFollowUpDraftResult> { const { data, error } = await client.rpc("prepare_backlink_outreach_follow_up_draft", { p_workspace_id: required(input.workspaceId), p_outreach_id: required(input.outreachId), p_attempt_id: required(input.attemptId), p_actor_user_id: required(input.actorUserId), p_subject: required(input.subject), p_body: required(input.body), p_prepared_at: required(input.preparedAt) }); if (error != null) throw normalize(error); if (!data || data.length !== 1) throw new BacklinkRepositoryError({ code: "DATABASE", operation: "followUpDraft", message: "Invalid follow-up draft result." }); const value = map(data[0], data[0].disposition === "created" ? "created" : data[0].disposition === "existing" ? "existing" : undefined); if (value.disposition == null) throw new BacklinkRepositoryError({ code: "DATABASE", operation: "followUpDraft", message: "Invalid follow-up draft result." }); return value as PrepareBacklinkOutreachFollowUpDraftResult; }
export async function updateBacklinkOutreachFollowUpDraft(client: { rpc(name: UpdateName, args: UpdateArgs): PromiseLike<{ data: UpdateRow[] | null; error: unknown }> }, input: UpdateBacklinkOutreachFollowUpDraftInput): Promise<BacklinkOutreachFollowUpDraftProjection> { const { data, error } = await client.rpc("update_backlink_outreach_follow_up_draft", { p_workspace_id: required(input.workspaceId), p_outreach_id: required(input.outreachId), p_attempt_id: required(input.attemptId), p_actor_user_id: required(input.actorUserId), p_subject: required(input.subject), p_body: required(input.body), p_expected_updated_at: required(input.expectedUpdatedAt), p_updated_at: required(input.updatedAt) }); if (error != null) throw normalize(error); if (!data || data.length !== 1) throw new BacklinkRepositoryError({ code: "DATABASE", operation: "followUpDraft", message: "Invalid follow-up draft result." }); return map(data[0]); }
