import { BacklinkRepositoryError, normalizeBacklinkRepositoryError } from "./errors";
import type { BacklinkRepositoryClient } from "./repositoryClient";
import type { WorkspaceId } from "./types";
import type { Database } from "@/types/database.types";

export type BacklinkOutreachAttemptRow = Database["public"]["Tables"]["backlink_outreach_attempts"]["Row"];
type BacklinkOutreachAttemptInsert = Database["public"]["Tables"]["backlink_outreach_attempts"]["Insert"];
export type CreateBacklinkOutreachAttemptInput = { outreachId: string; actorUserId: string; channel: string; provider: string; recipient: string; idempotencyKey: string };
export type BacklinkOutreachAttemptStatePatch = Pick<BacklinkOutreachAttemptInsert, "status" | "provider_message_id" | "error_code" | "error_message" | "accepted_at" | "failed_at" | "resolved_at">;
export type BacklinkOutreachAttemptReservation = { attempt: BacklinkOutreachAttemptRow; disposition: "created" | "existing" };

function required(value: string, field: string): string { const normalized = value.trim(); if (!normalized) throw new BacklinkRepositoryError({ code: "VALIDATION", operation: "createBacklinkOutreachAttempt", message: `${field} is required.` }); return normalized; }
export async function getBacklinkOutreachAttemptById(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, attemptId: string): Promise<BacklinkOutreachAttemptRow> { const { data, error } = await client.from("backlink_outreach_attempts").select("*").eq("workspace_id", workspaceId).eq("id", attemptId).maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("getBacklinkOutreachAttemptById", error); if (data == null) throw new BacklinkRepositoryError({ code: "NOT_FOUND", operation: "getBacklinkOutreachAttemptById", message: "The requested record was not found." }); return data; }
export async function getBacklinkOutreachAttemptByIdempotencyKey(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, idempotencyKey: string): Promise<BacklinkOutreachAttemptRow | null> { const { data, error } = await client.from("backlink_outreach_attempts").select("*").eq("workspace_id", workspaceId).eq("idempotency_key", idempotencyKey.trim()).maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("getBacklinkOutreachAttemptByIdempotencyKey", error); return data; }
export async function listBacklinkOutreachAttemptsForOutreach(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, outreachId: string): Promise<BacklinkOutreachAttemptRow[]> { const { data, error } = await client.from("backlink_outreach_attempts").select("*").eq("workspace_id", workspaceId).eq("outreach_id", outreachId).order("requested_at", { ascending: false }); if (error != null) throw normalizeBacklinkRepositoryError("listBacklinkOutreachAttemptsForOutreach", error); return data ?? []; }
export async function createBacklinkOutreachAttempt(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, input: CreateBacklinkOutreachAttemptInput): Promise<BacklinkOutreachAttemptRow> { const idempotencyKey = required(input.idempotencyKey, "idempotencyKey"); const payload: BacklinkOutreachAttemptInsert = { workspace_id: workspaceId, outreach_id: input.outreachId, actor_user_id: input.actorUserId, channel: input.channel, provider: required(input.provider, "provider"), recipient: required(input.recipient, "recipient"), idempotency_key: idempotencyKey, status: "requested" }; const { data, error } = await client.from("backlink_outreach_attempts").insert(payload).select("*").single(); if (error == null) return data; const normalized = normalizeBacklinkRepositoryError("createBacklinkOutreachAttempt", error); if (normalized.code !== "CONFLICT") throw normalized; const existing = await getBacklinkOutreachAttemptByIdempotencyKey(client, workspaceId, idempotencyKey); if (existing != null) return existing; throw normalized; }
export async function reserveBacklinkOutreachAttempt(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, input: CreateBacklinkOutreachAttemptInput): Promise<BacklinkOutreachAttemptReservation> { const idempotencyKey = required(input.idempotencyKey, "idempotencyKey"); const payload: BacklinkOutreachAttemptInsert = { workspace_id: workspaceId, outreach_id: input.outreachId, actor_user_id: input.actorUserId, channel: input.channel, provider: required(input.provider, "provider"), recipient: required(input.recipient, "recipient"), idempotency_key: idempotencyKey, status: "requested" }; const { data, error } = await client.from("backlink_outreach_attempts").insert(payload).select("*").single(); if (error == null) return { attempt: data, disposition: "created" }; const normalized = normalizeBacklinkRepositoryError("reserveBacklinkOutreachAttempt", error); if (normalized.code !== "CONFLICT") throw normalized; const existing = await getBacklinkOutreachAttemptByIdempotencyKey(client, workspaceId, idempotencyKey); if (existing != null) return { attempt: existing, disposition: "existing" }; throw normalized; }
export async function updateBacklinkOutreachAttemptState(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, attemptId: string, patch: BacklinkOutreachAttemptStatePatch): Promise<BacklinkOutreachAttemptRow> { const { data, error } = await client.from("backlink_outreach_attempts").update(patch).eq("workspace_id", workspaceId).eq("id", attemptId).select("*").maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("updateBacklinkOutreachAttemptState", error); if (data == null) throw new BacklinkRepositoryError({ code: "NOT_FOUND", operation: "updateBacklinkOutreachAttemptState", message: "The requested record was not found." }); return data; }
export async function resolveUnknownBacklinkOutreachAttemptState(client: BacklinkRepositoryClient, workspaceId: WorkspaceId, attemptId: string, patch: BacklinkOutreachAttemptStatePatch): Promise<BacklinkOutreachAttemptRow | null> { const { data, error } = await client.from("backlink_outreach_attempts").update(patch).eq("workspace_id", workspaceId).eq("id", attemptId).eq("status", "unknown").select("*").maybeSingle(); if (error != null) throw normalizeBacklinkRepositoryError("resolveUnknownBacklinkOutreachAttemptState", error); return data; }
