import type { Locale } from "@/data/i18n";

export type FreeAuditListingModeCopy = Readonly<{
  heroEyebrow: string;
  heroTitle: string;
  heroSubtitle: string;
  reassurance: string;
  formTitle: string;
  formText: string;
  listingUrlLabel: string;
  helper: string;
  submitIdle: string;
  submitLoading: string;
  statusLoading: string;
}>;

export const freeAuditListingModeCopy: Record<Locale, FreeAuditListingModeCopy> = {
  en: { heroEyebrow: "Free listing audit", heroTitle: "Test your listing for free", heroSubtitle: "Paste your public Airbnb, Booking, Expedia, Agoda or Vrbo listing URL to receive a partial Norixo audit before unlocking the full analysis.", reassurance: "No credit card. Only the public listing URL and the structured details you provide are sent for analysis.", formTitle: "Analyze your listing", formText: "Enter the public listing URL and its market details. Norixo will return a limited public preview of the audit.", listingUrlLabel: "Public listing URL", helper: "Your public listing URL is sent to Norixo to generate this partial audit.", submitIdle: "Run my free audit", submitLoading: "Analyzing listing...", statusLoading: "Partial listing audit in progress." },
  fr: { heroEyebrow: "Audit gratuit de l'annonce", heroTitle: "Testez gratuitement votre annonce", heroSubtitle: "Collez l'URL publique de votre annonce Airbnb, Booking, Expedia, Agoda ou Vrbo pour recevoir un audit Norixo partiel avant de débloquer l'analyse complète.", reassurance: "Aucune carte bancaire. Seuls l'URL publique et les renseignements structurés fournis sont envoyés pour l'analyse.", formTitle: "Analyser votre annonce", formText: "Saisissez l'URL publique de l'annonce et les informations de marché. Norixo renverra un aperçu limité de l'audit.", listingUrlLabel: "URL publique de l'annonce", helper: "L'URL publique de votre annonce est envoyée à Norixo afin de générer cet audit partiel.", submitIdle: "Lancer mon audit gratuit", submitLoading: "Analyse de l'annonce...", statusLoading: "Audit partiel de l'annonce en cours." },
  es: { heroEyebrow: "Auditoría gratuita del anuncio", heroTitle: "Prueba tu anuncio gratis", heroSubtitle: "Pega la URL pública de tu anuncio de Airbnb, Booking, Expedia, Agoda o Vrbo para recibir una auditoría parcial de Norixo antes de desbloquear el análisis completo.", reassurance: "Sin tarjeta. Solo se envían para el análisis la URL pública y los datos estructurados que proporciones.", formTitle: "Analiza tu anuncio", formText: "Introduce la URL pública y los datos de mercado. Norixo devolverá una vista previa limitada de la auditoría.", listingUrlLabel: "URL pública del anuncio", helper: "La URL pública se envía a Norixo para generar esta auditoría parcial.", submitIdle: "Iniciar mi auditoría gratis", submitLoading: "Analizando anuncio...", statusLoading: "Auditoría parcial en curso." },
  it: { heroEyebrow: "Audit gratuito dell'annuncio", heroTitle: "Prova gratuitamente il tuo annuncio", heroSubtitle: "Incolla l'URL pubblico del tuo annuncio Airbnb, Booking, Expedia, Agoda o Vrbo per ricevere un audit Norixo parziale prima di sbloccare l'analisi completa.", reassurance: "Nessuna carta. Per l'analisi vengono inviati solo l'URL pubblico e i dati strutturati forniti.", formTitle: "Analizza il tuo annuncio", formText: "Inserisci l'URL pubblico e i dati di mercato. Norixo restituirà un'anteprima limitata dell'audit.", listingUrlLabel: "URL pubblico dell'annuncio", helper: "L'URL pubblico viene inviato a Norixo per generare questo audit parziale.", submitIdle: "Avvia il mio audit gratuito", submitLoading: "Analisi annuncio...", statusLoading: "Audit parziale in corso." },
  pt: { heroEyebrow: "Auditoria gratuita do anúncio", heroTitle: "Teste gratuitamente o seu anúncio", heroSubtitle: "Cole o URL público do seu anúncio Airbnb, Booking, Expedia, Agoda ou Vrbo para receber uma auditoria parcial da Norixo antes de desbloquear a análise completa.", reassurance: "Sem cartão. Apenas o URL público e os dados estruturados fornecidos são enviados para análise.", formTitle: "Analise o seu anúncio", formText: "Introduza o URL público e os dados de mercado. A Norixo devolverá uma pré-visualização limitada da auditoria.", listingUrlLabel: "URL público do anúncio", helper: "O URL público é enviado à Norixo para gerar esta auditoria parcial.", submitIdle: "Iniciar auditoria gratuita", submitLoading: "A analisar anúncio...", statusLoading: "Auditoria parcial em curso." },
  nl: { heroEyebrow: "Gratis advertentie-audit", heroTitle: "Test je advertentie gratis", heroSubtitle: "Plak de openbare URL van je Airbnb-, Booking-, Expedia-, Agoda- of Vrbo-advertentie voor een gedeeltelijke Norixo-audit voordat je de volledige analyse ontgrendelt.", reassurance: "Geen creditcard. Alleen de openbare URL en de door jou verstrekte gestructureerde gegevens worden voor analyse verzonden.", formTitle: "Analyseer je advertentie", formText: "Voer de openbare URL en marktgegevens in. Norixo geeft een beperkte auditpreview terug.", listingUrlLabel: "Openbare advertentie-URL", helper: "De openbare URL wordt naar Norixo gestuurd om deze gedeeltelijke audit te genereren.", submitIdle: "Start mijn gratis audit", submitLoading: "Advertentie analyseren...", statusLoading: "Gedeeltelijke advertentie-audit wordt uitgevoerd." },
  de: { heroEyebrow: "Kostenloser Inserat-Audit", heroTitle: "Teste dein Inserat kostenlos", heroSubtitle: "Füge die öffentliche URL deines Airbnb-, Booking-, Expedia-, Agoda- oder Vrbo-Inserats ein und erhalte einen teilweisen Norixo-Audit, bevor du die vollständige Analyse freischaltest.", reassurance: "Keine Kreditkarte. Nur die öffentliche URL und die angegebenen strukturierten Daten werden zur Analyse gesendet.", formTitle: "Inserat analysieren", formText: "Gib die öffentliche URL und Marktdaten ein. Norixo liefert eine begrenzte Audit-Vorschau.", listingUrlLabel: "Öffentliche Inserat-URL", helper: "Die öffentliche URL wird an Norixo gesendet, um diesen teilweisen Audit zu erstellen.", submitIdle: "Kostenlosen Audit starten", submitLoading: "Inserat wird analysiert...", statusLoading: "Teilweiser Inserat-Audit läuft." },
  ja: { heroEyebrow: "無料リスティング監査", heroTitle: "リスティングを無料で診断", heroSubtitle: "Airbnb、Booking、Expedia、Agoda、Vrbo の公開リスティングURLを貼り付けると、完全分析を解除する前に Norixo の部分監査を受けられます。", reassurance: "クレジットカード不要。分析には公開URLと入力した構造化情報のみが送信されます。", formTitle: "リスティングを分析", formText: "公開URLと市場情報を入力してください。Norixo が限定された監査プレビューを返します。", listingUrlLabel: "公開リスティングURL", helper: "この部分監査を生成するため、公開URLが Norixo に送信されます。", submitIdle: "無料監査を開始", submitLoading: "リスティングを分析中...", statusLoading: "部分監査を実行中です。" },
  zh: { heroEyebrow: "免费房源审核", heroTitle: "免费测试你的房源", heroSubtitle: "粘贴 Airbnb、Booking、Expedia、Agoda 或 Vrbo 的公开房源 URL，在解锁完整分析前获得 Norixo 部分审核。", reassurance: "无需信用卡。仅会发送公开房源 URL 和你填写的结构化信息用于分析。", formTitle: "分析你的房源", formText: "输入公开房源 URL 和市场信息，Norixo 将返回有限的审核预览。", listingUrlLabel: "公开房源 URL", helper: "公开房源 URL 会发送给 Norixo，以生成此次部分审核。", submitIdle: "开始免费审核", submitLoading: "正在分析房源...", statusLoading: "部分房源审核进行中。" },
  ko: { heroEyebrow: "무료 숙소 감사", heroTitle: "숙소를 무료로 테스트하세요", heroSubtitle: "Airbnb, Booking, Expedia, Agoda 또는 Vrbo의 공개 숙소 URL을 붙여 넣으면 전체 분석을 잠금 해제하기 전에 Norixo 부분 감사를 받을 수 있습니다.", reassurance: "신용카드가 필요 없습니다. 분석에는 공개 URL과 입력한 구조화 정보만 전송됩니다.", formTitle: "숙소 분석", formText: "공개 URL과 시장 정보를 입력하세요. Norixo가 제한된 감사 미리보기를 제공합니다.", listingUrlLabel: "공개 숙소 URL", helper: "부분 감사를 생성하기 위해 공개 URL이 Norixo로 전송됩니다.", submitIdle: "무료 감사 시작", submitLoading: "숙소 분석 중...", statusLoading: "부분 숙소 감사 진행 중." },
  ar: { heroEyebrow: "تدقيق مجاني للإعلان", heroTitle: "اختبر إعلانك مجانًا", heroSubtitle: "ألصق الرابط العام لإعلانك على Airbnb أو Booking أو Expedia أو Agoda أو Vrbo للحصول على تدقيق جزئي من Norixo قبل فتح التحليل الكامل.", reassurance: "لا حاجة إلى بطاقة. يتم إرسال الرابط العام والبيانات المنظمة التي تقدمها فقط لأغراض التحليل.", formTitle: "حلّل إعلانك", formText: "أدخل الرابط العام وبيانات السوق. ستعرض Norixo معاينة محدودة من التدقيق.", listingUrlLabel: "الرابط العام للإعلان", helper: "يتم إرسال الرابط العام إلى Norixo لإنشاء هذا التدقيق الجزئي.", submitIdle: "بدء التدقيق المجاني", submitLoading: "جارٍ تحليل الإعلان...", statusLoading: "التدقيق الجزئي للإعلان جارٍ." },
};
