import { NextRequest, NextResponse } from "next/server";
import { isAdminPrivateEmail } from "@/lib/auth/isAdminEmail";
import { BACKLINK_ASSET_LIFECYCLE_STATUSES, createAsset, listAssets, type AssetInput } from "@/lib/backlinks/services/assetService";
import { getRequestUserAndWorkspace } from "@/lib/server/routeAuth";

function isRecord(body: unknown): body is Record<string, unknown> { return typeof body === "object" && body != null && !Array.isArray(body); }
function value(body: Record<string, unknown>, key: string) { const candidate = body[key]; return typeof candidate === "string" ? candidate : undefined; }
function lifecycleStatus(body: Record<string, unknown>) { const candidate = body.lifecycle_status; if (candidate === undefined) return undefined; return typeof candidate === "string" ? BACKLINK_ASSET_LIFECYCLE_STATUSES.find((status) => status === candidate) ?? null : null; }
function errorResponse(error: unknown) { const code = typeof error === "object" && error != null && "code" in error && typeof error.code === "string" ? error.code : null; const message = error instanceof Error ? error.message : "Impossible de traiter les assets."; return NextResponse.json({ error: message }, { status: code === "NOT_FOUND" ? 404 : code === "VALIDATION" ? 400 : code === "CONFLICT" ? 409 : code === "FORBIDDEN" ? 403 : 500 }); }
async function context(request: NextRequest) { const result = await getRequestUserAndWorkspace(request); if (result.status === "unauthenticated") return null; if (result.status === "workspace_forbidden") return "forbidden" as const; return isAdminPrivateEmail(result.user.email) ? { client: result.client, user: result.user, workspace: result.workspace } : "forbidden" as const; }
function assetInput(body: Record<string, unknown>): AssetInput | null { const asset_key = value(body, "asset_key"); const display_name = value(body, "display_name"); const asset_type = value(body, "asset_type"); const status = lifecycleStatus(body); if (status === null) return null; return asset_key && display_name && asset_type ? { asset_key, display_name, asset_type, ...(value(body, "description") !== undefined ? { description: value(body, "description") } : {}), ...(value(body, "canonical_url") !== undefined ? { canonical_url: value(body, "canonical_url") } : {}), ...(status !== undefined ? { lifecycle_status: status } : {}) } : null; }
export async function GET(request: NextRequest) { const requestContext = await context(request); if (requestContext == null) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (requestContext === "forbidden") return NextResponse.json({ error: "Forbidden" }, { status: 403 }); try { return NextResponse.json(await listAssets(requestContext.client, requestContext.workspace.id)); } catch (error) { return errorResponse(error); } }
export async function POST(request: NextRequest) { const requestContext = await context(request); if (requestContext == null) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (requestContext === "forbidden") return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const body: unknown = await request.json().catch(() => null); if (!isRecord(body)) return NextResponse.json({ error: "Invalid request body" }, { status: 400 }); const input = assetInput(body); if (!input) return NextResponse.json({ error: "Invalid request body" }, { status: 400 }); try { return NextResponse.json(await createAsset(requestContext.client, requestContext.workspace.id, requestContext.user.id, input), { status: 201 }); } catch (error) { return errorResponse(error); } }
