import type { PrepareBacklinksAutomationRunResult } from "./preparation-types";
import type { RunBacklinksAutomationSchedulerTickDependencies, RunBacklinksAutomationSchedulerTickInput, RunBacklinksAutomationSchedulerTickResult } from "./scheduler-tick-types";
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const PROMOTION_TASK_KIND="backlinks.promotion.preview";
function getPreparedTaskByKind(
  prepared: Extract<PrepareBacklinksAutomationRunResult, { kind: "prepared" }>,
  kind: "backlinks.discovery.preview" | "backlinks.qualification.preview" | "backlinks.promotion.preview",
) {
  const matches = prepared.tasks.filter((entry) => entry.task.taskKind === kind);
  if (matches.length !== 1) {
    throw new Error("promotion task must be a valid prepared promotion task");
  }
  return matches[0];
}
function validate(i:RunBacklinksAutomationSchedulerTickInput){if(!UUID.test(i.workspaceId))throw new Error("workspaceId must be a valid UUID");if(i.requestedBy!==null&&!UUID.test(i.requestedBy))throw new Error("requestedBy must be a valid UUID");if(!i.workerId.trim())throw new Error("workerId must not be empty");if(!i.idempotencyKey.trim()||i.idempotencyKey!==i.idempotencyKey.trim())throw new Error("idempotencyKey must not be empty");if(!["manual","scheduled","internal"].includes(i.triggerSource))throw new Error("triggerSource must be valid");for(const d of [i.scheduledAt,i.startedAt,i.attemptedAt,i.completedAt,i.failedAt])if(!Number.isFinite(Date.parse(d)))throw new Error("scheduler tick dates must be valid");if(!Number.isInteger(i.leaseDurationSeconds)||i.leaseDurationSeconds<30||i.leaseDurationSeconds>3600)throw new Error("leaseDurationSeconds must be an integer between 30 and 3600");if(!Number.isInteger(i.maxWorkerInvocations)||i.maxWorkerInvocations<1||i.maxWorkerInvocations>100)throw new Error("maxWorkerInvocations must be an integer between 1 and 100");for(const value of [i.discoveryInput,i.qualificationInput,i.promotionInput])if(typeof value!=="object"||value==null||Array.isArray(value))throw new Error("scheduler tick inputs must be JSON objects")}
export async function runBacklinksAutomationSchedulerTick(d:RunBacklinksAutomationSchedulerTickDependencies,i:RunBacklinksAutomationSchedulerTickInput):Promise<RunBacklinksAutomationSchedulerTickResult>{validate(i);const prepared=await d.prepareBacklinksDryRun({workspaceId:i.workspaceId,requestedBy:i.requestedBy,idempotencyKey:i.idempotencyKey,triggerSource:i.triggerSource,scheduledAt:i.scheduledAt,discoveryInput:i.discoveryInput,qualificationInput:i.qualificationInput,promotionInput:i.promotionInput});if(prepared.kind==="rejected")return prepared;const promotionEntry=getPreparedTaskByKind(prepared,PROMOTION_TASK_KIND);const promotionTask=promotionEntry.task;if(typeof promotionTask.id!="string"||!UUID.test(promotionTask.id)||promotionTask.workspaceId!==prepared.run.workspaceId||promotionTask.runId!==prepared.run.id)throw new Error("promotion task must be a valid prepared promotion task");const promotionTaskId=promotionTask.id;const preparation={runDisposition:prepared.runDisposition,taskDispositions:[getPreparedTaskByKind(prepared,"backlinks.discovery.preview").disposition,getPreparedTaskByKind(prepared,"backlinks.qualification.preview").disposition,getPreparedTaskByKind(prepared,"backlinks.promotion.preview").disposition] as const};const execution=await d.executeBacklinksDryRun({workspaceId:i.workspaceId,runId:prepared.run.id,workerId:i.workerId,startedAt:i.startedAt,attemptedAt:i.attemptedAt,completedAt:i.completedAt,failedAt:i.failedAt,leaseDurationSeconds:i.leaseDurationSeconds,maxWorkerInvocations:i.maxWorkerInvocations});if(execution.kind==="completed")return{kind:"completed",run:prepared.run,preparation,promotionTaskId,execution};if(execution.kind==="pending_retry")return{kind:"pending_retry",run:prepared.run,preparation,promotionTaskId,execution};return{kind:"failed",run:prepared.run,preparation,promotionTaskId,execution}}
