import type { AutomationTaskDependencies, CancelAutomationTaskInput, CancelAutomationTaskResult, ClaimNextAutomationTaskInput, ClaimNextAutomationTaskResult, CompleteAutomationTaskInput, CompleteAutomationTaskResult, CreateAutomationTaskInput, CreateAutomationTaskResult, FailAutomationTaskInput, FailAutomationTaskResult, HeartbeatAutomationTaskInput, HeartbeatAutomationTaskResult, ReclaimExpiredAutomationTasksInput, ReclaimExpiredAutomationTasksResult } from "./types";
function text(value: string, name: string): void { if (!value.trim()) throw new Error(`${name} must not be empty`); }
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function uuid(value: string, name: string): void { if (!UUID_PATTERN.test(value)) throw new Error(`${name} must be a valid UUID`); }
function date(value: string, name: string): void { if (!Number.isFinite(Date.parse(value))) throw new Error(`${name} must be a valid date`); }
function lease(value: number): void { if (!Number.isInteger(value) || value < 30 || value > 3600) throw new Error("leaseDurationSeconds must be an integer between 30 and 3600"); }
function base(input: { workspaceId: string; taskId?: string; runId?: string; workerId?: string }): void { text(input.workspaceId,"workspaceId"); uuid(input.workspaceId,"workspaceId"); if(input.taskId!=null) { text(input.taskId,"taskId"); uuid(input.taskId,"taskId"); } if(input.runId!=null) { text(input.runId,"runId"); uuid(input.runId,"runId"); } if(input.workerId!=null) text(input.workerId,"workerId"); }
export async function createAutomationTask(d: AutomationTaskDependencies,i: CreateAutomationTaskInput): Promise<CreateAutomationTaskResult>{base(i);text(i.taskKind,"taskKind");text(i.taskKey,"taskKey");date(i.scheduledAt,"scheduledAt");date(i.availableAt,"availableAt");if(typeof i.input!=="object"||i.input==null||Array.isArray(i.input))throw new Error("input must be a JSON object");return d.createOrGetTask(i)}
export async function claimNextAutomationTask(d: AutomationTaskDependencies,i: ClaimNextAutomationTaskInput): Promise<ClaimNextAutomationTaskResult>{base(i);date(i.claimedAt,"claimedAt");lease(i.leaseDurationSeconds);const task=await d.claimNextTask(i);return task==null?{kind:"empty"}:{kind:"claimed",task}}
export async function heartbeatAutomationTask(d: AutomationTaskDependencies,i: HeartbeatAutomationTaskInput): Promise<HeartbeatAutomationTaskResult>{base(i);date(i.heartbeatAt,"heartbeatAt");lease(i.leaseDurationSeconds);const task=await d.heartbeatTask(i);return task==null?{kind:"rejected",reason:"not_updated"}:{kind:"extended",task}}
export async function completeAutomationTask(d: AutomationTaskDependencies,i: CompleteAutomationTaskInput): Promise<CompleteAutomationTaskResult>{base(i);date(i.completedAt,"completedAt");if(i.output!=null&&(typeof i.output!=="object"||Array.isArray(i.output)))throw new Error("output must be a JSON object");const task=await d.completeTask(i);return task==null?{kind:"rejected",reason:"not_updated"}:{kind:"completed",task}}
export async function failAutomationTask(d: AutomationTaskDependencies,i: FailAutomationTaskInput): Promise<FailAutomationTaskResult>{base(i);date(i.failedAt,"failedAt");text(i.errorCode,"errorCode");text(i.errorMessage,"errorMessage");const task=await d.failTask(i);return task==null?{kind:"rejected",reason:"not_updated"}:task.status==="dead_letter"?{kind:"dead_letter",task}:{kind:"retried",task}}
export async function reclaimExpiredAutomationTasks(d: AutomationTaskDependencies,i: ReclaimExpiredAutomationTasksInput): Promise<ReclaimExpiredAutomationTasksResult>{base(i);date(i.reclaimedAt,"reclaimedAt");if(!Number.isInteger(i.limit)||i.limit<1||i.limit>100)throw new Error("limit must be an integer between 1 and 100");return{kind:"reclaimed",tasks:await d.reclaimExpiredTasks(i)}}
export async function cancelAutomationTask(d: AutomationTaskDependencies,i: CancelAutomationTaskInput): Promise<CancelAutomationTaskResult>{base(i);date(i.cancelledAt,"cancelledAt");const task=await d.cancelTask(i);return task==null?{kind:"rejected",reason:"not_updated"}:{kind:"cancelled",task}}
