import type { AutomationRunTransitionDependencies, CancelAutomationRunInput, CancelAutomationRunResult, CompleteAutomationRunInput, CompleteAutomationRunResult, FailAutomationRunInput, FailAutomationRunResult, StartAutomationRunInput, StartAutomationRunResult } from "./types";

function assertText(value: string, name: string): void { if (value.trim().length === 0) throw new Error(`${name} must not be empty`); }
function assertDate(value: string, name: string): void { if (!Number.isFinite(Date.parse(value))) throw new Error(`${name} must be a valid date`); }
function assertBase(input: { workspaceId: string; runId: string }, date: string, dateName: string): void { assertText(input.workspaceId, "workspaceId"); assertText(input.runId, "runId"); assertDate(date, dateName); }

export async function startAutomationRun(dependencies: AutomationRunTransitionDependencies, input: StartAutomationRunInput): Promise<StartAutomationRunResult> { assertBase(input, input.startedAt, "startedAt"); const run = await dependencies.startRun(input); return run == null ? { kind: "rejected", reason: "not_updated" } : { kind: "transitioned", run }; }
export async function completeAutomationRun(dependencies: AutomationRunTransitionDependencies, input: CompleteAutomationRunInput): Promise<CompleteAutomationRunResult> { assertBase(input, input.completedAt, "completedAt"); const run = await dependencies.completeRun(input); return run == null ? { kind: "rejected", reason: "not_updated" } : { kind: "transitioned", run }; }
export async function failAutomationRun(dependencies: AutomationRunTransitionDependencies, input: FailAutomationRunInput): Promise<FailAutomationRunResult> { assertBase(input, input.failedAt, "failedAt"); assertText(input.errorCode, "errorCode"); assertText(input.errorMessage, "errorMessage"); const run = await dependencies.failRun(input); return run == null ? { kind: "rejected", reason: "not_updated" } : { kind: "transitioned", run }; }
export async function cancelAutomationRun(dependencies: AutomationRunTransitionDependencies, input: CancelAutomationRunInput): Promise<CancelAutomationRunResult> { assertBase(input, input.cancelledAt, "cancelledAt"); if (input.reason != null) assertText(input.reason, "reason"); const run = await dependencies.cancelRun(input); return run == null ? { kind: "rejected", reason: "not_updated" } : { kind: "transitioned", run }; }
