import { buildBacklinksDryRunPlan, type BuildBacklinksDryRunPlanInput } from "../lib/automation";

function assert(condition: boolean, message: string): asserts condition { if (!condition) throw new Error(message); }
function assertThrows(operation: () => void, message: string): void { try { operation(); } catch (error) { assert(error instanceof Error && error.message.includes(message), message); return; } throw new Error("Expected throw"); }

const input: BuildBacklinksDryRunPlanInput = { workspaceId: "00000000-0000-4000-8000-000000000001", runId: "00000000-0000-4000-8000-000000000002", scheduledAt: "2026-08-04T10:00:00.000Z", discoveryInput: { sources: ["seed"] }, qualificationInput: { candidates: ["candidate"] } };
function assertTaskKeys(task: Record<string, unknown>): void { assert(JSON.stringify(Object.keys(task).sort()) === JSON.stringify(["availableAt","input","priority","runId","scheduledAt","system","taskKey","taskKind","workspaceId"].sort()), "Exact task keys"); }
function main(): void { const before = JSON.stringify(input); const first = buildBacklinksDryRunPlan(input); const second = buildBacklinksDryRunPlan(input); assert(JSON.stringify(Object.keys(first)) === JSON.stringify(["tasks"]), "Plan must only contain tasks"); assert(first.tasks.length === 2, "Exactly two tasks"); const [discovery, qualification] = first.tasks; assert(discovery.workspaceId === input.workspaceId && discovery.runId === input.runId && discovery.system === "backlinks" && discovery.taskKind === "backlinks.discovery.preview" && discovery.taskKey === "discovery-preview" && discovery.priority === 10 && discovery.scheduledAt === input.scheduledAt && discovery.availableAt === input.scheduledAt && discovery.input === input.discoveryInput, "Discovery task"); assert(qualification.workspaceId === input.workspaceId && qualification.runId === input.runId && qualification.system === "backlinks" && qualification.taskKind === "backlinks.qualification.preview" && qualification.taskKey === "qualification-preview" && qualification.priority === 20 && qualification.scheduledAt === input.scheduledAt && qualification.availableAt === input.scheduledAt && qualification.input === input.qualificationInput, "Qualification task"); assertTaskKeys(discovery); assertTaskKeys(qualification); assert(JSON.stringify(first) === JSON.stringify(second) && second.tasks[0].input === input.discoveryInput && second.tasks[1].input === input.qualificationInput, "Deterministic references"); assert(JSON.stringify(input) === before, "Input must not mutate"); assertThrows(() => buildBacklinksDryRunPlan({ ...input, workspaceId: "" }), "workspaceId must be a valid UUID"); assertThrows(() => buildBacklinksDryRunPlan({ ...input, workspaceId: "bad" }), "workspaceId must be a valid UUID"); assertThrows(() => buildBacklinksDryRunPlan({ ...input, runId: "" }), "runId must be a valid UUID"); assertThrows(() => buildBacklinksDryRunPlan({ ...input, scheduledAt: "bad" }), "scheduledAt must be a valid date"); const other = buildBacklinksDryRunPlan({ ...input, workspaceId: "00000000-0000-4000-8000-000000000003", runId: "00000000-0000-4000-8000-000000000004", discoveryInput: { sources: [] }, qualificationInput: { candidates: [] } }); assert(other.tasks[0].workspaceId !== discovery.workspaceId && other.tasks[0].runId !== discovery.runId && other.tasks[0].input !== discovery.input, "Independent plans"); console.log("PASS — Automation Backlinks dry-run plan smoke"); }
main();
