import { executeBacklinksDryRunOrchestrator, type AutomationRun, type AutomationTask, type ExecuteAutomationWorkerOnceResult, type ExecuteBacklinksDryRunOrchestratorDependencies } from "../lib/automation";
function assert(c:boolean,m:string):asserts c{if(!c)throw new Error(m)}
const i={workspaceId:"00000000-0000-4000-8000-000000000001",runId:"00000000-0000-4000-8000-000000000002",workerId:"worker-A",startedAt:"2026-08-04T10:00:00.000Z",attemptedAt:"2026-08-04T10:00:00.000Z",completedAt:"2026-08-04T10:00:00.000Z",failedAt:"2026-08-04T10:00:00.000Z",leaseDurationSeconds:30,maxWorkerInvocations:3};const run:AutomationRun={id:i.runId,workspaceId:i.workspaceId,system:"backlinks",runKind:"x",idempotencyKey:"x",status:"running",mode:"dry_run",triggerSource:"manual",requestedBy:null,scheduledAt:i.startedAt,startedAt:i.startedAt,completedAt:null,failedAt:null,cancelledAt:null,heartbeatAt:null,leaseExpiresAt:null,workerId:null,attemptCount:1,maxAttempts:1,input:{},summary:null,errorCode:null,errorMessage:null,createdAt:i.startedAt,updatedAt:i.startedAt};const task:AutomationTask={id:"00000000-0000-4000-8000-000000000003",workspaceId:i.workspaceId,runId:i.runId,system:"backlinks",taskKind:"noop",taskKey:"x",status:"completed",priority:1,scheduledAt:i.startedAt,availableAt:i.startedAt,claimedAt:null,startedAt:null,heartbeatAt:null,leaseExpiresAt:null,completedAt:i.completedAt,failedAt:null,cancelledAt:null,workerId:null,attemptCount:1,maxAttempts:3,backoffBaseSeconds:60,input:{},output:null,errorCode:null,errorMessage:null,createdAt:i.startedAt,updatedAt:i.startedAt};
function deps(results: ExecuteAutomationWorkerOnceResult[]): ExecuteBacklinksDryRunOrchestratorDependencies {
  let n = 0;
  return { startRun: async () => ({ kind: "transitioned", run }), executeWorkerOnce: async () => results[n++] ?? { kind: "empty" }, completeRun: async () => ({ kind: "transitioned", run }), failRun: async () => ({ kind: "transitioned", run }) };
}
async function main(){let complete=0,fail=0;const d=deps([{kind:"completed",task,output:{}},{kind:"completed",task,output:{}},{kind:"empty"}]);d.completeRun=async x=>{complete++;assert(JSON.stringify(x.summary)===JSON.stringify({workerInvocations:3,completedTasks:2,retriedTasks:0,deadLetterTasks:0,stoppedBecause:"empty"}),"summary");return{kind:"transitioned",run}};d.failRun=async()=>{fail++;return{kind:"transitioned",run}};const completed=await executeBacklinksDryRunOrchestrator(d,i);assert(completed.kind==="completed"&&complete===1&&fail===0,"completed");const pending=await executeBacklinksDryRunOrchestrator(deps([{kind:"retried",task},{kind:"empty"}]),i);assert(pending.kind==="pending_retry","pending");const dead=await executeBacklinksDryRunOrchestrator(deps([{kind:"dead_letter",task},{kind:"empty"}]),i);assert(dead.kind==="failed","dead");const limit=await executeBacklinksDryRunOrchestrator(deps([{kind:"completed",task,output:{}},{kind:"completed",task,output:{}}]),{...i,maxWorkerInvocations:2});assert(limit.kind==="completed"&&limit.stoppedBecause==="max_worker_invocations","limit");const rejected=deps([]);rejected.startRun=async()=>({kind:"rejected",reason:"not_updated"});let threw=false;try{await executeBacklinksDryRunOrchestrator(rejected,i)}catch(e){threw=e instanceof Error&&e.message==="AUTOMATION_RUN_START_REJECTED"}assert(threw,"start reject");console.log("PASS — Automation Backlinks dry-run orchestrator smoke")}
void main();
