import { cancelAutomationRun, completeAutomationRun, failAutomationRun, startAutomationRun, type AutomationRun, type AutomationRunTransitionDependencies } from "../lib/automation";
function assert(condition: boolean, message: string): asserts condition { if (!condition) throw new Error(message); }
const base: AutomationRun = { id: "00000000-0000-4000-8000-000000000002", workspaceId: "00000000-0000-4000-8000-000000000001", system: "backlinks", runKind: "smoke", idempotencyKey: "smoke", status: "queued", mode: "dry_run", triggerSource: "manual", requestedBy: null, scheduledAt: "2026-08-03T10:00:00.000Z", startedAt: null, completedAt: null, failedAt: null, cancelledAt: null, heartbeatAt: null, leaseExpiresAt: null, workerId: null, attemptCount: 0, maxAttempts: 1, input: {}, summary: null, errorCode: null, errorMessage: null, createdAt: "2026-08-03T10:00:00.000Z", updatedAt: "2026-08-03T10:00:00.000Z" };
const dependencies: AutomationRunTransitionDependencies = { startRun: async () => ({ ...base, status: "running", startedAt: base.scheduledAt }), completeRun: async () => ({ ...base, status: "completed", startedAt: base.scheduledAt, completedAt: base.scheduledAt }), failRun: async () => ({ ...base, status: "failed", startedAt: base.scheduledAt, failedAt: base.scheduledAt, errorCode: "FAIL", errorMessage: "Failed" }), cancelRun: async () => ({ ...base, status: "cancelled", cancelledAt: base.scheduledAt }) };
async function main(): Promise<void> {
  const start = await startAutomationRun(dependencies, { workspaceId: base.workspaceId, runId: base.id, startedAt: base.scheduledAt }); assert(start.kind === "transitioned" && start.run.status === "running", "Expected queued to running.");
  const complete = await completeAutomationRun(dependencies, { workspaceId: base.workspaceId, runId: base.id, completedAt: base.scheduledAt, summary: null }); assert(complete.kind === "transitioned" && complete.run.status === "completed", "Expected running to completed.");
  const failed = await failAutomationRun(dependencies, { workspaceId: base.workspaceId, runId: base.id, failedAt: base.scheduledAt, errorCode: "FAIL", errorMessage: "Failed" }); assert(failed.kind === "transitioned" && failed.run.status === "failed", "Expected running to failed.");
  const cancelled = await cancelAutomationRun(dependencies, { workspaceId: base.workspaceId, runId: base.id, cancelledAt: base.scheduledAt, reason: null }); assert(cancelled.kind === "transitioned" && cancelled.run.status === "cancelled", "Expected cancellation.");
  const rejected = await startAutomationRun({ ...dependencies, startRun: async () => null }, { workspaceId: base.workspaceId, runId: base.id, startedAt: base.scheduledAt }); assert(rejected.kind === "rejected" && rejected.reason === "not_updated", "Invalid state must reject.");
  const failure = new Error("repository failure"); let thrown: unknown; try { await cancelAutomationRun({ ...dependencies, cancelRun: async () => { throw failure; } }, { workspaceId: base.workspaceId, runId: base.id, cancelledAt: base.scheduledAt, reason: null }); } catch (error) { thrown = error; } assert(thrown === failure, "Repository error must propagate by identity.");
  console.log("PASS — Automation run transition service smoke");
}
void main();
