import { readFile } from "node:fs/promises";
function assert(value: unknown, message: string): asserts value { if (!value) throw new Error(message); }
function between(source: string, start: string, end: string) { const from = source.indexOf(start); const to = source.indexOf(end, from); assert(from >= 0 && to > from, `Missing function block: ${start}`); return source.slice(from, to); }
async function main() { const [sql, types, fix] = await Promise.all([readFile("supabase/migrations/20260811157000_add_backlink_outreach_follow_up_drafts.sql", "utf8"), readFile("types/database.types.ts", "utf8"), readFile("supabase/migrations/20260917180000_fix_backlink_outreach_follow_up_draft_rpc_ambiguity.sql", "utf8")]); for (const value of ["create table public.backlink_outreach_follow_up_drafts", "unique (attempt_id)", "follow_up_number integer not null check (follow_up_number > 0)", "char_length(subject) between 1 and 300", "char_length(body) between 1 and 10000", "prepared_at timestamptz not null", "updated_at timestamptz not null", "updated_by uuid not null", "enable row level security", "is_workspace_member(workspace_id)", "prepare_backlink_outreach_follow_up_draft", "update_backlink_outreach_follow_up_draft"]) assert(sql.includes(value), `Missing D3 schema invariant: ${value}`); assert(!sql.includes("for insert to authenticated") && !sql.includes("for update to authenticated"), "No authenticated draft writes."); for (const value of ["backlink_outreach_follow_up_drafts:", "follow_up_number: number", "prepare_backlink_outreach_follow_up_draft:", "update_backlink_outreach_follow_up_draft:"]) assert(types.includes(value), `Missing D3 type: ${value}`);
  const prepare = between(fix, "create or replace function public.prepare_backlink_outreach_follow_up_draft", "create or replace function public.update_backlink_outreach_follow_up_draft");
  const update = between(fix, "create or replace function public.update_backlink_outreach_follow_up_draft", "revoke all on function public.prepare_backlink_outreach_follow_up_draft");
  for (const value of ["returns table (disposition text, draft_id uuid, outreach_id uuid, attempt_id uuid", "security definer set search_path = public", "attempt.id=p_attempt_id and attempt.workspace_id=p_workspace_id and attempt.outreach_id=p_outreach_id", "draft.attempt_id=a.id", "a.attempt_kind <> 'follow_up' or a.status <> 'prepared'", "if found then return query select 'existing'", "insert into public.backlink_outreach_follow_up_drafts", "return query select 'created'"]) assert(prepare.includes(value), `Missing prepare RPC invariant: ${value}`);
  for (const value of ["returns table (draft_id uuid, outreach_id uuid, attempt_id uuid", "security definer set search_path = public", "attempt.id=p_attempt_id and attempt.workspace_id=p_workspace_id and attempt.outreach_id=p_outreach_id", "draft.workspace_id=p_workspace_id and draft.outreach_id=p_outreach_id and draft.attempt_id=p_attempt_id and draft.updated_at=p_expected_updated_at", "a.attempt_kind <> 'follow_up' or a.status <> 'prepared'", "FOLLOW_UP_DRAFT_CONFLICT", "return query select d.id,d.outreach_id,d.attempt_id"]) assert(update.includes(value), `Missing update RPC invariant: ${value}`);
  for (const value of ["where id=p_attempt_id", "and outreach_id=p_outreach_id", "where attempt_id=a.id"]) assert(!prepare.includes(value), `Prepare RPC retains ambiguous reference: ${value}`);
  for (const value of ["where id=p_attempt_id", "and outreach_id=p_outreach_id", "where workspace_id=p_workspace_id", "and attempt_id=p_attempt_id", "and updated_at=p_expected_updated_at"]) assert(!update.includes(value), `Update RPC retains ambiguous reference: ${value}`);
  for (const value of ["revoke all on function public.prepare_backlink_outreach_follow_up_draft", "grant execute on function public.prepare_backlink_outreach_follow_up_draft", "revoke all on function public.update_backlink_outreach_follow_up_draft", "grant execute on function public.update_backlink_outreach_follow_up_draft"]) assert(fix.includes(value), `Missing retained draft RPC grant invariant: ${value}`);
  console.log("PASS — Backlink follow-up drafts schema smoke"); }
void main();
