import { BacklinkOutreachLifecycleError, transitionBacklinkOutreachLifecycle } from "../lib/backlinks/services/outreachLifecycleService";
import type { BacklinkOutreachRow } from "../lib/backlinks/repositories/outreachRepository";
function assert(v: unknown, m: string): asserts v { if (!v) throw new Error(m); }
const now = "2026-08-10T12:00:00.000Z";
function row(status: string = "active", response: string | null = null): BacklinkOutreachRow { return { id:"o", workspace_id:"w", campaign_id:"c", opportunity_id:"p", contact_id:"ct", outreach_key:"BL-OUT-2026-001", channel:"email", status, current_attempt:3, max_attempts:3, first_contact_at:null,last_attempt_at:null,next_follow_up_at:"future",response_deadline_at:"deadline",closed_at:null,last_response_type:response,stop_reason:null,created_by:null,created_at:now,updated_at:now,subject:null,body:null }; }
async function main() { let value=row(); let patches: Record<string, unknown>[]=[]; const service=transitionBacklinkOutreachLifecycle({getOutreach:async()=>value,updateIfStatus:async(_w,_id,expected,patch)=>{ patches.push(patch); if(value.status!==expected)return null; value={...value,...patch}; return value;},now:()=>now}); const input={workspaceId:"w",actorUserId:"actor",outreachId:"o"};
 for(const responseType of ["positive","negative","neutral","bounced","unsubscribed"] as const){value=row(); const r=await service({...input,transition:{kind:"mark_replied",responseType}}); assert(r.status==="replied"&&value.last_response_type===responseType&&value.closed_at===null&&value.stop_reason===null&&value.next_follow_up_at===null&&value.response_deadline_at===null,"reply patch");}
 value=row("replied","positive"); assert((await service({...input,transition:{kind:"open_conversation"}})).status==="conversation_open"&&value.response_deadline_at===null,"conversation"); value=row("replied","neutral"); try{await service({...input,transition:{kind:"open_conversation"}});throw 0}catch(e){assert(e instanceof BacklinkOutreachLifecycleError&&e.code==="OUTREACH_LIFECYCLE_RESPONSE_TYPE_INVALID","invalid conversation");}
 value=row(); assert((await service({...input,transition:{kind:"decline",stopReason:" reason "}})).status==="declined"&&value.stop_reason==="reason"&&value.closed_at===now&&value.response_deadline_at===null,"decline"); value=row(); assert((await service({...input,transition:{kind:"mark_no_response"}})).status==="no_response"&&value.stop_reason==="attempt_limit"&&value.last_response_type===null&&value.response_deadline_at===null,"no response"); value=row(); value.current_attempt=2; try{await service({...input,transition:{kind:"mark_no_response"}});throw 0}catch(e){assert(e instanceof BacklinkOutreachLifecycleError&&e.code==="OUTREACH_LIFECYCLE_NO_RESPONSE_ATTEMPTS_REMAIN","limit");}
 value=row("active","neutral"); assert((await service({...input,transition:{kind:"pause"}})).status==="paused"&&value.last_response_type==="neutral"&&value.response_deadline_at===null,"pause"); value=row("active","neutral"); assert((await service({...input,transition:{kind:"close",stopReason:" close "}})).status==="closed"&&value.stop_reason==="close"&&value.last_response_type==="neutral"&&value.response_deadline_at===null,"close"); for(const patch of patches)for(const key of Object.keys(patch))assert(["status","last_response_type","closed_at","stop_reason","next_follow_up_at","response_deadline_at"].includes(key),`patch ${key}`); console.log("PASS — Backlink outreach manual lifecycle service smoke"); }
void main();
