/** Villes Maroc (échantillon + saisie libre si absent). */
const cities: string[] = [
  "Agadir",
  "Asilah",
  "Azrou",
  "Béni Mellal",
  "Berkane",
  "Casablanca",
  "Chefchaouen",
  "Dakhla",
  "El Jadida",
  "Errachidia",
  "Essaouira",
  "Fès",
  "Ifrane",
  "Kénitra",
  "Khénifra",
  "Laâyoune",
  "Larache",
  "Marrakech",
  "Meknès",
  "Mohammedia",
  "Nador",
  "Ouarzazate",
  "Oujda",
  "Rabat",
  "Safi",
  "Sidi Bouzid",
  "Sidi Ifni",
  "Tanger",
  "Taza",
  "Témara",
  "Tétouan",
  "Zagora",
];

export default cities;
