import type { KnowledgeObject } from "../types";

export const accommodationRevenueKnowledgeObject: KnowledgeObject = {
  identity: {
    canonicalId: "revenue.accommodation-revenue",
    canonicalName: "Accommodation Revenue",
    slug: "accommodation-revenue",
    aliases: ["rental revenue", "stay revenue"],
    abbreviations: [],
    translations: {
      en: { canonicalName: "Accommodation Revenue", aliases: ["rental revenue"] },
      fr: { canonicalName: "revenu d’hébergement", aliases: ["revenu locatif"] },
    },
    parentConcepts: [
      { canonicalId: "domains.revenue-metrics", rationale: "Accommodation Revenue is a revenue input." },
    ],
    childConcepts: [],
    siblingConcepts: [],
    relatedConcepts: [],
    status: "validated",
    version: "1.0.0",
    owner: "Norixo research team",
    reviewDate: "2026-07-24",
    evidenceLevel: "E3",
  },
  definition: {
    shortDefinition: "Revenue attributed to guest accommodation for a defined measurement period under a stated revenue convention.",
    longDefinition:
      "Accommodation Revenue is the revenue assigned to the stay itself before the selected treatment of cleaning fees, taxes, refundable deposits, and platform commissions. It is an input to ADR and RevPAR, and must use a consistent convention when periods or providers are compared.",
    purpose: "Define the revenue numerator used in rate and revenue-efficiency calculations.",
    scope: ["Guest accommodation revenue", "Measurement period", "Stated revenue convention"],
    outOfScope: ["Net profit", "Refundable deposits", "Universal fee treatment", "PMS-specific reconciliation"],
    commonMisunderstandings: [
      "Accommodation Revenue is not automatically equivalent to gross or net revenue.",
      "Cleaning fees, taxes, and commissions are not universally treated the same way.",
    ],
    terminologyNotes: ["Revenue fields can vary between channel managers, PMS providers, and data platforms."],
    calculationRelevance: "Accommodation Revenue is the numerator of ADR and direct RevPAR.",
    businessRelevance: "Provides the revenue basis for interpreting achieved rate and available-night revenue.",
    unitsAndDimensions: ["Currency in a defined period"],
    formulaReferences: [
      "ADR = accommodation revenue ÷ booked nights",
      "RevPAR = accommodation revenue ÷ available nights",
    ],
    conventionVariants: [
      "Cleaning fees can be included or excluded if treated consistently.",
      "Taxes and refundable deposits should not be conflated with accommodation revenue.",
      "Platform commissions can be reported before or after deduction depending on the source.",
      "Gross and net revenue are distinct concepts and are not registered in this patch.",
    ],
  },
  evidence: {
    primarySources: [
      {
        title: "AirDNA: How does AirDNA calculate average daily rate (ADR)?",
        url: "https://help.airdna.co/en/articles/8062173-how-does-airdna-calculate-average-daily-rate-adr",
        sourceType: "primary",
        supports: ["ADR revenue definition", "Cleaning-fee and service-fee treatment"],
      },
    ],
    secondarySources: [
      {
        title: "PriceLabs: Portfolio Analytics terminology",
        url: "https://help.pricelabs.co/portal/en/kb/articles/portfolio-analytics-terminology",
        sourceType: "secondary",
        supports: ["PMS revenue-component variation"],
      },
    ],
    internalMethodologyReferences: [
      {
        title: "Norixo KPI calculator calculation convention",
        identifier: "app/(default)/tools/[tool]/page.tsx",
        sourceType: "internal",
        supports: ["Norixo Accommodation Revenue convention"],
      },
    ],
    confidence: "High for the input definition; revenue inclusions remain provider-specific.",
    lastValidation: "2026-07-24",
    citationRules: [
      "Cite provider-specific treatment of fees, taxes, and commissions close to the claim.",
      "Do not describe one revenue convention as universal.",
    ],
    externalReferences: [],
    internalReferences: ["/tools/airbnb-adr-calculator", "/tools/airbnb-revpar-calculator"],
    limitations: ["The object does not reconcile gross revenue, net revenue, or provider-specific ledger fields."],
    contradictoryEvidence: ["PMS and data platforms can include different revenue components."],
  },
  relationships: {
    requires: [],
    dependsOn: [],
    relatedTo: [],
    oftenConfusedWith: [],
    opposite: [],
    derivedFrom: [],
    uses: [],
    usedBy: [
      { canonicalId: "metrics.average-daily-rate", rationale: "Numerator of the ADR formula." },
      {
        canonicalId: "metrics.revenue-per-available-rental-night",
        rationale: "Numerator of the direct RevPAR formula.",
      },
    ],
    calculatorReferences: ["/tools/airbnb-adr-calculator", "/tools/airbnb-revpar-calculator"],
    guideReferences: [],
    articleReferences: [],
    researchReferences: [],
    apiReferences: [],
  },
  editorialProjections: [],
  structuredKnowledge: {
    canonicalUrls: [],
    entity: "Accommodation Revenue",
    entityType: "metric_input",
    schemaSuitability: "deferred",
    schemaTypes: [],
    secondaryKeywords: [],
    semanticKeywords: ["cleaning fees", "taxes", "refundable deposits", "commissions"],
    localeCoverage: { en: "planned", fr: "planned" },
    internalImportance: "critical",
    externalLinkability: "contextual",
    retrievalEligibility: "eligible",
    apiEligibility: "pending_design",
  },
  internalLinking: {
    requiredInboundLinks: [],
    requiredOutboundLinks: [],
    anchorGuidance: ["No public projection exists yet."],
    canonicalDestinations: [],
    linkRationales: [],
    duplicationGuard: "No public projection exists yet.",
    projectionSpecificRules: ["Do not create a URL until a canonical public projection is approved."],
  },
  quality: {
    requiredChecks: ["Definition", "Revenue convention limits", "KPI reciprocal links"],
    validationRecord: "2026-07-24",
    privacyReview: "not_applicable",
    translationReview: "required",
    structuredDataReview: "not_applicable",
  },
  lifecycle: {
    stateHistory: [
      { status: "draft", date: "2026-07-24", reason: "Initial KPI input object created." },
      { status: "validated", date: "2026-07-24", reason: "KPI input relations reviewed." },
    ],
    reviewFrequency: "Annual or after a material provider-convention change.",
    versionHistory: ["1.0.0"],
    breakingChangePolicy: "Create a major version for definition or revenue-convention changes.",
    ownershipTransferHistory: [],
  },
};
