import type { KnowledgeObject } from "../types";

export const availableNightsKnowledgeObject: KnowledgeObject = {
  identity: {
    canonicalId: "inventory.available-nights",
    canonicalName: "Available Nights",
    slug: "available-nights",
    aliases: ["available rental nights", "sellable nights"],
    abbreviations: [],
    translations: {
      en: { canonicalName: "Available Nights" },
      fr: { canonicalName: "nuits disponibles" },
    },
    parentConcepts: [
      { canonicalId: "domains.inventory-metrics", rationale: "Available Nights define rental inventory." },
    ],
    childConcepts: [],
    siblingConcepts: [],
    relatedConcepts: [
      { canonicalId: "inventory.booked-nights", rationale: "Both describe a booking period's inventory." },
    ],
    status: "validated",
    version: "1.0.0",
    owner: "Norixo research team",
    reviewDate: "2026-07-24",
    evidenceLevel: "E3",
  },
  definition: {
    shortDefinition: "Nights included in the available rental inventory for a defined measurement period.",
    longDefinition:
      "Available Nights are the nights counted as open to guest bookings in a measurement period. They may differ from all calendar nights when blocked dates, owner stays, or maintenance closures are excluded by the selected availability convention.",
    purpose: "Define the denominator used to measure calendar utilisation and revenue per available night.",
    scope: ["Measurement period", "Rental inventory", "Availability convention"],
    outOfScope: ["All calendar nights by default", "Booked nights", "Revenue", "Profit"],
    commonMisunderstandings: [
      "Calendar nights are not always available nights.",
      "Blocked nights and booked nights must not be treated as identical inputs.",
    ],
    terminologyNotes: ["Providers may use active, adjusted, or full-calendar availability definitions."],
    calculationRelevance: "Available Nights are the denominator of Occupancy and RevPAR.",
    businessRelevance: "Makes calendar utilisation and revenue-efficiency comparisons interpretable.",
    unitsAndDimensions: ["Count of nights in a defined period"],
    formulaReferences: [
      "Occupancy = booked nights ÷ available nights × 100",
      "RevPAR = accommodation revenue ÷ available nights",
    ],
    conventionVariants: [
      "Blocked nights may be excluded from adjusted availability.",
      "Owner stays and maintenance closures can be excluded when intentionally unavailable to guests.",
      "Some providers use full calendar inventory instead.",
    ],
  },
  evidence: {
    primarySources: [
      {
        title: "AirDNA: How does AirDNA calculate occupancy rate?",
        url: "https://help.airdna.co/en/articles/8062178-how-does-airdna-calculate-occupancy-rate",
        sourceType: "primary",
        supports: ["Active listing nights", "Blocked-night and availability treatment"],
      },
    ],
    secondarySources: [
      {
        title: "PriceLabs: Report Builder metrics",
        url: "https://help.pricelabs.co/portal/en/kb/articles/a-complete-guide-to-report-builder-metrics",
        sourceType: "secondary",
        supports: ["Adjusted and total availability conventions"],
      },
    ],
    internalMethodologyReferences: [
      {
        title: "Norixo KPI calculator calculation convention",
        identifier: "app/(default)/tools/[tool]/page.tsx",
        sourceType: "internal",
        supports: ["Norixo Available Nights convention"],
      },
    ],
    confidence: "High for the input definition; provider inventory conventions remain variable.",
    lastValidation: "2026-07-24",
    citationRules: ["Cite the selected blocked-night and availability convention close to the claim."],
    externalReferences: [],
    internalReferences: ["/tools/airbnb-occupancy-calculator", "/tools/airbnb-revpar-calculator"],
    limitations: ["No universal availability denominator applies across all PMS and data providers."],
    contradictoryEvidence: ["Providers can include or exclude unavailable inventory differently."],
  },
  relationships: {
    requires: [],
    dependsOn: [],
    relatedTo: [],
    oftenConfusedWith: [],
    opposite: [],
    derivedFrom: [],
    uses: [],
    usedBy: [
      { canonicalId: "metrics.occupancy-rate", rationale: "Denominator of the occupancy formula." },
      {
        canonicalId: "metrics.revenue-per-available-rental-night",
        rationale: "Denominator of the direct RevPAR formula.",
      },
    ],
    calculatorReferences: ["/tools/airbnb-occupancy-calculator", "/tools/airbnb-revpar-calculator"],
    guideReferences: [],
    articleReferences: [],
    researchReferences: [],
    apiReferences: [],
  },
  editorialProjections: [],
  structuredKnowledge: {
    canonicalUrls: [],
    entity: "Available Nights",
    entityType: "metric_input",
    schemaSuitability: "deferred",
    schemaTypes: [],
    secondaryKeywords: [],
    semanticKeywords: ["calendar nights", "blocked nights", "owner stays", "maintenance closures"],
    localeCoverage: { en: "planned", fr: "planned" },
    internalImportance: "critical",
    externalLinkability: "contextual",
    retrievalEligibility: "eligible",
    apiEligibility: "pending_design",
  },
  internalLinking: {
    requiredInboundLinks: [],
    requiredOutboundLinks: [],
    anchorGuidance: ["No public projection exists yet."],
    canonicalDestinations: [],
    linkRationales: [],
    duplicationGuard: "No public projection exists yet.",
    projectionSpecificRules: ["Do not create a URL until a canonical public projection is approved."],
  },
  quality: {
    requiredChecks: ["Definition", "Provider convention limits", "KPI reciprocal links"],
    validationRecord: "2026-07-24",
    privacyReview: "not_applicable",
    translationReview: "required",
    structuredDataReview: "not_applicable",
  },
  lifecycle: {
    stateHistory: [
      { status: "draft", date: "2026-07-24", reason: "Initial KPI input object created." },
      { status: "validated", date: "2026-07-24", reason: "KPI input relations reviewed." },
    ],
    reviewFrequency: "Annual or after a material provider-convention change.",
    versionHistory: ["1.0.0"],
    breakingChangePolicy: "Create a major version for definition or denominator changes.",
    ownershipTransferHistory: [],
  },
};
