import type { KnowledgeObject } from "../types";

export const bookedNightsKnowledgeObject: KnowledgeObject = {
  identity: {
    canonicalId: "inventory.booked-nights",
    canonicalName: "Booked Nights",
    slug: "booked-nights",
    aliases: ["reserved nights"],
    abbreviations: [],
    translations: {
      en: { canonicalName: "Booked Nights", aliases: ["reserved nights"] },
      fr: { canonicalName: "nuits réservées" },
    },
    parentConcepts: [],
    childConcepts: [],
    siblingConcepts: [],
    relatedConcepts: [
      { canonicalId: "inventory.available-nights", rationale: "Both describe a booking period's inventory." },
    ],
    status: "validated",
    version: "1.0.0",
    owner: "Norixo research team",
    reviewDate: "2026-07-24",
    evidenceLevel: "E3",
  },
  definition: {
    shortDefinition: "Nights reserved by guests within a defined measurement period.",
    longDefinition:
      "Booked Nights count the individual nights covered by guest reservations in a measurement period. They are not the number of reservations, and their treatment may differ when reservations are cancelled, unpaid, owner-held, or represented differently by a PMS or data provider.",
    purpose: "Define the booking-volume input used in rate and occupancy calculations.",
    scope: ["Guest reservation nights", "Measurement period", "Reservation-status convention"],
    outOfScope: ["Reservation count", "Owner stays", "Blocked nights", "Revenue"],
    commonMisunderstandings: [
      "One reservation can contain multiple booked nights.",
      "Booked nights are not necessarily identical to occupied nights in every provider dataset.",
    ],
    terminologyNotes: ["PMS and data providers can use different cancellation, payment, or stay-status conventions."],
    calculationRelevance: "Booked Nights are the denominator of ADR and numerator of Occupancy.",
    businessRelevance: "Connects reservation activity to achieved rate and calendar utilisation.",
    unitsAndDimensions: ["Count of nights in a defined period"],
    formulaReferences: [
      "ADR = accommodation revenue ÷ booked nights",
      "Occupancy = booked nights ÷ available nights × 100",
    ],
    conventionVariants: [
      "Cancelled reservations may be excluded depending on the reporting status.",
      "Owner or complimentary stays should be distinguished from guest bookings.",
      "PMS and provider booking-status rules can differ.",
    ],
  },
  evidence: {
    primarySources: [
      {
        title: "AirDNA: How does AirDNA calculate occupancy rate?",
        url: "https://help.airdna.co/en/articles/8062178-how-does-airdna-calculate-occupancy-rate",
        sourceType: "primary",
        supports: ["Reserved-day treatment", "Booked and blocked-night distinction"],
      },
    ],
    secondarySources: [
      {
        title: "PriceLabs: Report Builder metrics",
        url: "https://help.pricelabs.co/portal/en/kb/articles/a-complete-guide-to-report-builder-metrics",
        sourceType: "secondary",
        supports: ["Paid and adjusted occupancy variants"],
      },
    ],
    internalMethodologyReferences: [
      {
        title: "Norixo KPI calculator calculation convention",
        identifier: "app/(default)/tools/[tool]/page.tsx",
        sourceType: "internal",
        supports: ["Norixo Booked Nights convention"],
      },
    ],
    confidence: "High for the input definition; booking-status conventions remain variable.",
    lastValidation: "2026-07-24",
    citationRules: ["Cite provider-specific cancellation or booking-status treatment close to the claim."],
    externalReferences: [],
    internalReferences: ["/tools/airbnb-adr-calculator", "/tools/airbnb-occupancy-calculator"],
    limitations: ["Reservation status and occupancy interpretation can differ across PMS and providers."],
    contradictoryEvidence: ["Providers may use different paid, reserved, or occupied-night definitions."],
  },
  relationships: {
    requires: [],
    dependsOn: [],
    relatedTo: [],
    oftenConfusedWith: [],
    opposite: [],
    derivedFrom: [],
    uses: [],
    usedBy: [
      { canonicalId: "metrics.average-daily-rate", rationale: "Denominator of the ADR formula." },
      { canonicalId: "metrics.occupancy-rate", rationale: "Numerator of the occupancy formula." },
    ],
    calculatorReferences: ["/tools/airbnb-adr-calculator", "/tools/airbnb-occupancy-calculator"],
    guideReferences: [],
    articleReferences: [],
    researchReferences: [],
    apiReferences: [],
  },
  editorialProjections: [],
  structuredKnowledge: {
    canonicalUrls: [],
    entity: "Booked Nights",
    entityType: "metric_input",
    schemaSuitability: "deferred",
    schemaTypes: [],
    secondaryKeywords: [],
    semanticKeywords: ["reservations", "occupancy", "cancellations", "owner stays"],
    localeCoverage: { en: "planned", fr: "planned" },
    internalImportance: "critical",
    externalLinkability: "contextual",
    retrievalEligibility: "eligible",
    apiEligibility: "pending_design",
  },
  internalLinking: {
    requiredInboundLinks: [],
    requiredOutboundLinks: [],
    anchorGuidance: ["No public projection exists yet."],
    canonicalDestinations: [],
    linkRationales: [],
    duplicationGuard: "No public projection exists yet.",
    projectionSpecificRules: ["Do not create a URL until a canonical public projection is approved."],
  },
  quality: {
    requiredChecks: ["Definition", "Booking-status limits", "KPI reciprocal links"],
    validationRecord: "2026-07-24",
    privacyReview: "not_applicable",
    translationReview: "required",
    structuredDataReview: "not_applicable",
  },
  lifecycle: {
    stateHistory: [
      { status: "draft", date: "2026-07-24", reason: "Initial KPI input object created." },
      { status: "validated", date: "2026-07-24", reason: "KPI input relations reviewed." },
    ],
    reviewFrequency: "Annual or after a material provider-convention change.",
    versionHistory: ["1.0.0"],
    breakingChangePolicy: "Create a major version for definition or booking-status changes.",
    ownershipTransferHistory: [],
  },
};
