import type { KnowledgeObject } from "../types";

export const revenueManagementKnowledgeObject: KnowledgeObject = {
  identity: {
    canonicalId: "domains.revenue-management",
    canonicalName: "Revenue Management",
    slug: "revenue-management",
    aliases: ["rental revenue management"],
    abbreviations: [],
    translations: {
      en: { canonicalName: "Revenue Management" },
      fr: { canonicalName: "gestion des revenus" },
    },
    parentConcepts: [],
    childConcepts: [
      { canonicalId: "domains.revenue-metrics", rationale: "Revenue metrics are a core decision input." },
      { canonicalId: "domains.inventory-metrics", rationale: "Inventory metrics are a core decision input." },
    ],
    siblingConcepts: [],
    relatedConcepts: [],
    status: "validated",
    version: "1.0.0",
    owner: "Norixo research team",
    reviewDate: "2026-07-24",
    evidenceLevel: "E1",
  },
  definition: {
    shortDefinition: "The decision discipline that combines price, demand, availability, and performance to optimise revenue.",
    longDefinition:
      "Revenue Management provides the canonical taxonomy for decisions that combine pricing, demand, availability, and performance analysis in short-term rentals.",
    purpose: "Classify the concepts used to make revenue-optimisation decisions.",
    scope: ["Revenue Metrics", "Inventory Metrics", "Pricing", "Forecasting", "Performance analysis", "Future optimisation strategies"],
    outOfScope: ["Accounting", "General property management", "Housekeeping operations", "Generic CRM"],
    commonMisunderstandings: ["Revenue Management is broader than a single pricing metric.", "It does not replace accounting or operational management."],
    terminologyNotes: ["This is a classification object, not a calculable KPI."],
    calculationRelevance: "Provides the parent domain for KPI and inventory inputs used in revenue decisions.",
    businessRelevance: "Creates a stable taxonomy for performance and optimisation knowledge.",
    unitsAndDimensions: [],
    formulaReferences: [],
    conventionVariants: [],
  },
  evidence: {
    primarySources: [],
    secondarySources: [],
    internalMethodologyReferences: [{ title: "Norixo Knowledge Object Contract", identifier: "lib/knowledge/types.ts", sourceType: "internal", supports: ["Domain classification contract"] }],
    confidence: "Internal taxonomy classification reviewed for the initial KPI cluster.",
    lastValidation: "2026-07-24",
    citationRules: ["Do not present this internal taxonomy as an external industry standard."],
    externalReferences: [],
    internalReferences: [],
    limitations: ["This domain does not define pricing, forecasting, or optimisation methods."],
    contradictoryEvidence: [],
  },
  relationships: { requires: [], dependsOn: [], relatedTo: [], oftenConfusedWith: [], opposite: [], derivedFrom: [], uses: [], usedBy: [], calculatorReferences: [], guideReferences: [], articleReferences: [], researchReferences: [], apiReferences: [] },
  editorialProjections: [],
  structuredKnowledge: { canonicalUrls: [], entity: "Revenue Management", entityType: "knowledge_domain", schemaSuitability: "deferred", schemaTypes: [], secondaryKeywords: [], semanticKeywords: ["pricing", "forecasting", "performance analysis", "availability"], localeCoverage: { en: "planned", fr: "planned" }, internalImportance: "critical", externalLinkability: "none", retrievalEligibility: "eligible", apiEligibility: "pending_design" },
  internalLinking: { requiredInboundLinks: [], requiredOutboundLinks: [], anchorGuidance: ["No public projection exists yet."], canonicalDestinations: [], linkRationales: [], duplicationGuard: "No public projection exists yet.", projectionSpecificRules: ["Do not create a URL until a canonical public projection is approved."] },
  quality: { requiredChecks: ["Definition", "Hierarchy reciprocity", "Lifecycle"], validationRecord: "2026-07-24", privacyReview: "not_applicable", translationReview: "required", structuredDataReview: "not_applicable" },
  lifecycle: { stateHistory: [{ status: "draft", date: "2026-07-24", reason: "Initial canonical domain object created." }, { status: "validated", date: "2026-07-24", reason: "Initial taxonomy hierarchy reviewed." }], reviewFrequency: "Annual or when the canonical taxonomy materially changes.", versionHistory: ["1.0.0"], breakingChangePolicy: "Create a major version for a material domain-scope change.", ownershipTransferHistory: [] },
};
