import type { KnowledgeObject } from "../types";

export const revenueMetricsKnowledgeObject: KnowledgeObject = {
  identity: {
    canonicalId: "domains.revenue-metrics",
    canonicalName: "Revenue Metrics",
    slug: "revenue-metrics",
    aliases: ["rental revenue metrics"],
    abbreviations: [],
    translations: { en: { canonicalName: "Revenue Metrics" }, fr: { canonicalName: "métriques de revenus" } },
    parentConcepts: [{ canonicalId: "domains.revenue-management", rationale: "Revenue metrics support revenue-management decisions." }],
    childConcepts: [
      { canonicalId: "metrics.average-daily-rate", rationale: "ADR measures revenue per booked night." },
      { canonicalId: "metrics.revenue-per-available-rental-night", rationale: "RevPAR measures revenue per available night." },
      { canonicalId: "revenue.accommodation-revenue", rationale: "Accommodation Revenue is a revenue input." },
    ],
    siblingConcepts: [],
    relatedConcepts: [],
    status: "validated",
    version: "1.0.0",
    owner: "Norixo research team",
    reviewDate: "2026-07-24",
    evidenceLevel: "E1",
  },
  definition: {
    shortDefinition: "Concepts used to measure accommodation revenue and financial performance.",
    longDefinition: "Revenue Metrics is the canonical domain for concepts used to measure accommodation revenue and financial performance for a rental.",
    purpose: "Classify revenue measures and inputs within the knowledge graph.",
    scope: ["Average Daily Rate", "Revenue per Available Rental Night", "Accommodation Revenue", "Future revenue metrics"],
    outOfScope: ["Pricing strategy", "Distribution", "Operational costs", "General accounting"],
    commonMisunderstandings: ["Revenue Metrics does not define pricing strategy.", "Revenue metrics are not a substitute for profitability accounting."],
    terminologyNotes: ["This is a classification object, not a calculable KPI."],
    calculationRelevance: "Groups revenue measures and revenue inputs used by calculations.",
    businessRelevance: "Organises financial-performance concepts for consistent analysis.",
    unitsAndDimensions: [], formulaReferences: [], conventionVariants: [],
  },
  evidence: {
    primarySources: [], secondarySources: [],
    internalMethodologyReferences: [{ title: "Norixo Knowledge Object Contract", identifier: "lib/knowledge/types.ts", sourceType: "internal", supports: ["Domain classification contract"] }],
    confidence: "Internal taxonomy classification reviewed for the initial KPI cluster.", lastValidation: "2026-07-24",
    citationRules: ["Do not present this internal taxonomy as an external industry standard."], externalReferences: [], internalReferences: [], limitations: ["This domain does not define provider-specific revenue conventions."], contradictoryEvidence: [],
  },
  relationships: { requires: [], dependsOn: [], relatedTo: [], oftenConfusedWith: [], opposite: [], derivedFrom: [], uses: [], usedBy: [], calculatorReferences: [], guideReferences: [], articleReferences: [], researchReferences: [], apiReferences: [] },
  editorialProjections: [],
  structuredKnowledge: { canonicalUrls: [], entity: "Revenue Metrics", entityType: "knowledge_domain", schemaSuitability: "deferred", schemaTypes: [], secondaryKeywords: [], semanticKeywords: ["ADR", "RevPAR", "accommodation revenue", "rental performance"], localeCoverage: { en: "planned", fr: "planned" }, internalImportance: "high", externalLinkability: "none", retrievalEligibility: "eligible", apiEligibility: "pending_design" },
  internalLinking: { requiredInboundLinks: [], requiredOutboundLinks: [], anchorGuidance: ["No public projection exists yet."], canonicalDestinations: [], linkRationales: [], duplicationGuard: "No public projection exists yet.", projectionSpecificRules: ["Do not create a URL until a canonical public projection is approved."] },
  quality: { requiredChecks: ["Definition", "Hierarchy reciprocity", "Lifecycle"], validationRecord: "2026-07-24", privacyReview: "not_applicable", translationReview: "required", structuredDataReview: "not_applicable" },
  lifecycle: { stateHistory: [{ status: "draft", date: "2026-07-24", reason: "Initial canonical domain object created." }, { status: "validated", date: "2026-07-24", reason: "Initial taxonomy hierarchy reviewed." }], reviewFrequency: "Annual or when the canonical taxonomy materially changes.", versionHistory: ["1.0.0"], breakingChangePolicy: "Create a major version for a material domain-scope change.", ownershipTransferHistory: [] },
};
