begin;
create table public.automation_tasks (
 id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, run_id uuid not null references public.automation_runs(id) on delete cascade, system text not null, task_kind text not null, task_key text not null, status text not null default 'queued', priority integer not null default 100, scheduled_at timestamptz not null, available_at timestamptz not null, claimed_at timestamptz, started_at timestamptz, heartbeat_at timestamptz, lease_expires_at timestamptz, completed_at timestamptz, failed_at timestamptz, cancelled_at timestamptz, worker_id text, attempt_count integer not null default 0, max_attempts integer not null default 3, backoff_base_seconds integer not null default 60, input jsonb not null default '{}'::jsonb, output jsonb, error_code text, error_message text, created_at timestamptz not null default timezone('utc',now()), updated_at timestamptz not null default timezone('utc',now()),
 constraint automation_tasks_unique unique(workspace_id,run_id,task_kind,task_key), constraint automation_tasks_system check(system='backlinks'), constraint automation_tasks_kind check(task_kind=trim(task_kind) and char_length(task_kind)>0), constraint automation_tasks_key check(task_key=trim(task_key) and char_length(task_key)>0), constraint automation_tasks_status check(status in ('queued','running','completed','failed','cancelled','dead_letter')), constraint automation_tasks_priority check(priority between 0 and 1000000), constraint automation_tasks_attempts check(attempt_count>=0 and max_attempts>=1 and attempt_count<=max_attempts), constraint automation_tasks_backoff check(backoff_base_seconds>=1), constraint automation_tasks_worker check(worker_id is null or char_length(trim(worker_id))>0), constraint automation_tasks_input check(jsonb_typeof(input)='object'), constraint automation_tasks_output check(output is null or jsonb_typeof(output)='object'), constraint automation_tasks_error check((error_code is null or char_length(trim(error_code))>0) and (error_message is null or char_length(trim(error_message))>0)),
 constraint automation_tasks_state check((status='queued' and claimed_at is null and started_at is null and completed_at is null and failed_at is null and cancelled_at is null and worker_id is null and lease_expires_at is null) or (status='running' and claimed_at is not null and started_at is not null and heartbeat_at is not null and lease_expires_at is not null and worker_id is not null and completed_at is null and failed_at is null and cancelled_at is null) or (status='completed' and started_at is not null and completed_at is not null and failed_at is null and cancelled_at is null and error_code is null and error_message is null) or (status='failed' and failed_at is not null and completed_at is null and cancelled_at is null and error_code is not null and error_message is not null) or (status='dead_letter' and failed_at is not null and completed_at is null and cancelled_at is null and attempt_count=max_attempts and error_code is not null and error_message is not null) or (status='cancelled' and cancelled_at is not null and completed_at is null and failed_at is null))
);
create index automation_tasks_claim_idx on public.automation_tasks(status,available_at,priority,scheduled_at,created_at);
create index automation_tasks_workspace_run_status_idx on public.automation_tasks(workspace_id,run_id,status);
create index automation_tasks_lease_recovery_idx on public.automation_tasks(status,lease_expires_at) where status='running';
create or replace function public.validate_automation_task_integrity() returns trigger language plpgsql security definer set search_path=public as $$ begin if not exists(select 1 from public.automation_runs r where r.id=new.run_id and r.workspace_id=new.workspace_id and r.system=new.system and r.status in ('queued','running')) then raise exception 'AUTOMATION_TASK_RUN_WORKSPACE_OR_STATE_MISMATCH'; end if; return new; end; $$;
create trigger trg_automation_tasks_integrity before insert or update of workspace_id,run_id,system on public.automation_tasks for each row execute function public.validate_automation_task_integrity();
create trigger trg_automation_tasks_workspace_immutable before update of workspace_id on public.automation_tasks for each row execute function public.prevent_automation_workspace_reassignment();
create trigger trg_automation_tasks_updated_at before update on public.automation_tasks for each row execute function public.set_automation_updated_at();
alter table public.automation_tasks enable row level security;
create policy "automation_tasks_select_members" on public.automation_tasks for select to authenticated using(public.is_workspace_member(workspace_id));
create policy "automation_tasks_insert_admins" on public.automation_tasks for insert to authenticated with check(public.is_workspace_admin_or_owner(workspace_id));
create or replace function public.claim_next_automation_task(p_workspace_id uuid,p_run_id uuid,p_worker_id text,p_claimed_at timestamptz,p_lease_duration_seconds integer) returns setof public.automation_tasks language plpgsql security definer set search_path=public as $$ declare task public.automation_tasks; begin if p_workspace_id is null or p_run_id is null or p_claimed_at is null or char_length(trim(coalesce(p_worker_id,'')))=0 or p_lease_duration_seconds not between 30 and 3600 then raise exception 'AUTOMATION_TASK_INVALID_CLAIM'; end if; select t.* into task from public.automation_tasks t join public.automation_runs r on r.id=t.run_id join public.automation_workspace_controls c on c.workspace_id=t.workspace_id where t.workspace_id=p_workspace_id and t.run_id=p_run_id and t.status='queued' and t.available_at<=p_claimed_at and t.attempt_count<t.max_attempts and r.status in ('queued','running') and c.backlinks_enabled and c.dry_run_only order by t.priority,t.available_at,t.scheduled_at,t.created_at for update of t skip locked limit 1; if not found then return; end if; update public.automation_tasks set status='running',attempt_count=attempt_count+1,worker_id=p_worker_id,claimed_at=p_claimed_at,started_at=p_claimed_at,heartbeat_at=p_claimed_at,lease_expires_at=p_claimed_at+make_interval(secs=>p_lease_duration_seconds),error_code=null,error_message=null,failed_at=null where id=task.id returning * into task; return next task; end; $$;
create or replace function public.heartbeat_automation_task(p_workspace_id uuid,p_task_id uuid,p_worker_id text,p_heartbeat_at timestamptz,p_lease_duration_seconds integer) returns setof public.automation_tasks language plpgsql security definer set search_path=public as $$ declare task public.automation_tasks; begin update public.automation_tasks set heartbeat_at=p_heartbeat_at,lease_expires_at=p_heartbeat_at+make_interval(secs=>p_lease_duration_seconds) where workspace_id=p_workspace_id and id=p_task_id and status='running' and worker_id=p_worker_id and lease_expires_at>p_heartbeat_at returning * into task; if found then return next task; end if; end; $$;
create or replace function public.complete_automation_task(p_workspace_id uuid,p_task_id uuid,p_worker_id text,p_completed_at timestamptz,p_output jsonb) returns setof public.automation_tasks language plpgsql security definer set search_path=public as $$ declare task public.automation_tasks; begin update public.automation_tasks set status='completed',completed_at=p_completed_at,output=p_output,lease_expires_at=null where workspace_id=p_workspace_id and id=p_task_id and status='running' and worker_id=p_worker_id and lease_expires_at>p_completed_at returning * into task; if found then return next task; end if; end; $$;
create or replace function public.fail_automation_task(p_workspace_id uuid,p_task_id uuid,p_worker_id text,p_failed_at timestamptz,p_error_code text,p_error_message text) returns setof public.automation_tasks language plpgsql security definer set search_path=public as $$ declare task public.automation_tasks; begin update public.automation_tasks set status=case when attempt_count<max_attempts then 'queued' else 'dead_letter' end,available_at=case when attempt_count<max_attempts then p_failed_at+make_interval(secs=>least(86400,backoff_base_seconds*(2^(attempt_count-1))::integer)) else available_at end,worker_id=case when attempt_count<max_attempts then null else worker_id end,claimed_at=case when attempt_count<max_attempts then null else claimed_at end,started_at=case when attempt_count<max_attempts then null else started_at end,heartbeat_at=case when attempt_count<max_attempts then null else heartbeat_at end,lease_expires_at=null,failed_at=case when attempt_count<max_attempts then null else p_failed_at end,error_code=nullif(trim(p_error_code),''),error_message=nullif(trim(p_error_message),'') where workspace_id=p_workspace_id and id=p_task_id and status='running' and worker_id=p_worker_id and lease_expires_at>p_failed_at returning * into task; if found then return next task; end if; end; $$;
create or replace function public.reclaim_expired_automation_tasks(p_workspace_id uuid,p_run_id uuid,p_reclaimed_at timestamptz,p_limit integer) returns setof public.automation_tasks language plpgsql security definer set search_path=public as $$ begin if p_limit not between 1 and 100 then raise exception 'AUTOMATION_TASK_INVALID_RECLAIM_LIMIT'; end if; return query with candidates as(select id from public.automation_tasks where workspace_id=p_workspace_id and run_id=p_run_id and status='running' and lease_expires_at<=p_reclaimed_at order by lease_expires_at,created_at for update skip locked limit p_limit) update public.automation_tasks t set status=case when attempt_count<max_attempts then 'queued' else 'dead_letter' end,available_at=case when attempt_count<max_attempts then p_reclaimed_at else available_at end,worker_id=case when attempt_count<max_attempts then null else worker_id end,claimed_at=case when attempt_count<max_attempts then null else claimed_at end,started_at=case when attempt_count<max_attempts then null else started_at end,heartbeat_at=case when attempt_count<max_attempts then null else heartbeat_at end,lease_expires_at=null,failed_at=case when attempt_count<max_attempts then null else p_reclaimed_at end,error_code='AUTOMATION_TASK_LEASE_EXPIRED',error_message='Automation task lease expired' from candidates where t.id=candidates.id returning t.*; end; $$;
create or replace function public.cancel_automation_task(p_workspace_id uuid,p_task_id uuid,p_worker_id text,p_cancelled_at timestamptz) returns setof public.automation_tasks language plpgsql security definer set search_path=public as $$ declare task public.automation_tasks; begin update public.automation_tasks set status='cancelled',cancelled_at=p_cancelled_at,lease_expires_at=null where workspace_id=p_workspace_id and id=p_task_id and (status='queued' or (status='running' and worker_id=p_worker_id)) returning * into task; if found then return next task; end if; end; $$;
revoke all on function public.claim_next_automation_task(uuid,uuid,text,timestamptz,integer),public.heartbeat_automation_task(uuid,uuid,text,timestamptz,integer),public.complete_automation_task(uuid,uuid,text,timestamptz,jsonb),public.fail_automation_task(uuid,uuid,text,timestamptz,text,text),public.reclaim_expired_automation_tasks(uuid,uuid,timestamptz,integer),public.cancel_automation_task(uuid,uuid,text,timestamptz) from public,anon,authenticated;
grant execute on function public.claim_next_automation_task(uuid,uuid,text,timestamptz,integer),public.heartbeat_automation_task(uuid,uuid,text,timestamptz,integer),public.complete_automation_task(uuid,uuid,text,timestamptz,jsonb),public.fail_automation_task(uuid,uuid,text,timestamptz,text,text),public.reclaim_expired_automation_tasks(uuid,uuid,timestamptz,integer),public.cancel_automation_task(uuid,uuid,text,timestamptz) to service_role;
commit;
