// Tous les textes de Nomad Studio, en français. Seuls les noms officiels
// (YouTube, ElevenLabs, API, OAuth, JSON…) restent tels quels.

export const COPY = {
  title: "Nomad Studio",
  kicker: "Votre usine de production vidéo par IA",
  subtitle: "Pilotez l'ensemble de votre chaîne de production vidéo depuis une seule interface.",
  navLabel: "Sections de Nomad Studio",
  anchors: [
    ["system", "Système"],
    ["pipeline", "Pipeline"],
    ["planner", "Planificateur"],
    ["productions", "Productions"],
    ["comments", "Commentaires"],
    ["analytics", "Analytiques"],
    ["learning", "Apprentissage"],
    ["journal", "Journal"],
    ["settings", "Paramètres"],
  ] as const,
  hero: {
    activeVideo: "Vidéo active",
    nextProduction: "Prochaine production",
    lastRender: "Dernier rendu",
    lastSync: "Dernière synchronisation",
    overall: "État général",
    none: "Aucune",
    notAvailable: "Pas encore disponible",
    quickActions: "Actions rapides",
    actions: {
      newProduction: "Nouvelle production",
      relaunch: "Relancer la production",
      diagnostics: "Lancer le diagnostic",
      refresh: "Actualiser les données",
      journal: "Voir le journal",
    },
    checking: "Vérification…",
    notePending: "Nouvelle production et Relancer la production sont inactives : elles ne sont pas encore reliées à un moteur.",
    noteOffline: "Actualiser les données et Voir le journal nécessitent une connexion à l'agent.",
  },
  states: {
    ready: "Connecté",
    degraded: "Connecté, avec des points d'attention",
    blocked: "Indisponible",
    checking: "Vérification de la connexion…",
  },
  summaries: {
    ready: "Le pont local répond correctement.",
    degraded: "Connecté, avec un point d'attention : l'agent contient encore peu ou pas de données.",
  },
  system: {
    kicker: "Salle de contrôle",
    title: "État du système",
    currentEpisode: "Épisode en cours",
    version: "Version",
    latency: "Latence",
    overall: "État général",
    lastSync: "Dernière synchronisation",
    latestProduction: "dernière production",
    subsystems: "État des sous-systèmes",
  },
  tiles: {
    agent: "Agent",
    bridge: "Pont local",
    workflow: "Workflow",
    planner: "Planificateur",
    comments: "Commentaires",
    analytics: "Analytiques",
    learning: "Apprentissage",
    voice: "Voix",
    assembly: "Montage",
    quality: "Contrôle qualité",
  } as Record<string, string>,
  captions: {
    responding: "Répond",
    authenticated: "Authentifié",
    notAuthenticated: "Non authentifié",
    transitions: (n: number) => `${n} transitions`,
    ready: "Prêt",
    unavailable: "Indisponible",
    notConnected: "Non connecté",
    connected: "Connecté",
    readOnly: "Lecture seule",
    done: "Terminé",
    running: "En cours",
    failed: "En échec",
    pending: "En attente",
  },
  dots: { ok: "OK", warn: "Attention", error: "Erreur", idle: "Non connecté" },
  activity: {
    title: "Activité en cours",
    idle: "Rien n'est en cours pour le moment.",
    lastAction: "Dernière action enregistrée",
    badges: { running: "En cours", locked: "Verrouillée", last_action: "Dernière action", idle: "Au repos" },
    running: (stage: string, title: string | null) => `${stage} en cours${title ? ` sur « ${title} »` : ""}.`,
    locked: (title: string) => `« ${title} » est verrouillée : une exécution est en cours ou a été interrompue.`,
  },
  resources: {
    title: "Utilisation des ressources",
    note: "Carte réservée. Les mesures apparaîtront lorsqu'une source d'utilisation sera connectée.",
    badge: "Réservé",
    items: ["Calcul", "Crédits API", "Stockage", "Temps de rendu"],
  },
  waiting: "En attente de connexion",
  pipeline: {
    kicker: "Chaîne de production",
    title: "Pipeline",
    showing: (title: string) => `Production affichée : « ${title} ».`,
    none: "Aucune production active à afficher.",
    emptyTitle: "Aucune production active",
    emptyHint: "Le pipeline affiche la production en cours la plus pertinente.",
    complete: (n: number) => `${n} % terminé`,
    ariaStages: "Étapes du pipeline",
    footnote: "Le pipeline ne fournit qu'un statut par étape : une étape n'affiche 100 % que lorsqu'elle est terminée.",
    stages: {
      research: "Recherche",
      script: "Script",
      storyboard: "Storyboard",
      assets: "Ressources",
      voice: "Voix",
      assembly: "Montage",
      quality: "Contrôle qualité",
      publication: "Publication",
    } as Record<string, string>,
    status: { done: "Terminé", running: "En cours", failed: "En échec", pending: "En attente", not_connected: "Non connecté" } as Record<string, string>,
  },
  productions: {
    kicker: "Épisodes",
    title: "Productions",
    description: "Chaque carte est un épisode. La progression reflète les étapes du pipeline réellement terminées.",
    technicalSwitch: "Afficher les productions techniques",
    technicalHidden: (n: number) => ` (${n} masquées)`,
    tabsLabel: "État des épisodes",
    tabs: { planned: "Prévues", in_progress: "En cours", published: "Publiées" } as Record<string, string>,
    episode: "Épisode",
    technical: "Technique",
    locked: "Verrouillée",
    thumbnail: "Miniature à venir",
    progress: "Progression",
    targetDate: "Date prévue",
    duration: "Durée",
    video: "Vidéo",
    notLinked: "Non liée",
    empty: (label: string) => `Aucun épisode « ${label.toLowerCase()} »`,
    emptyHidden: "Les productions techniques (essais et exécutions échouées) sont masquées. Un épisode réel apparaît dès qu'il est lié à une vidéo.",
    emptyShown: "Aucune production ne correspond à ce filtre.",
    truncated: (inspected: number, total: number) => `Seules les ${inspected} productions les plus récentes sont inspectées (${total} détectées).`,
  },
  comments: {
    kicker: "Communauté",
    title: "Commentaires",
    description: "Chaque réponse est proposée, vérifiée, puis validée par un humain. Rien n'est jamais envoyé automatiquement.",
    safeguardsLabel: "Garde-fous des commentaires",
    safeguards: ["Aucune réponse automatique", "Validation humaine obligatoire", "Texte des commentaires traité comme non fiable"],
    ingestion: "Ingestion : en attente de connexion",
    empty: "Aucun commentaire à traiter",
    emptyHint: "Aucune source de commentaires n'est connectée. Les colonnes se rempliront lorsque l'ingestion sera disponible.",
    columns: { new: "En attente", priority: "Prioritaires", fact_check: "Vérification", proposed: "Réponses proposées", human_review: "Validation", published: "Terminés" } as Record<string, string>,
    actions: ["Valider", "Modifier", "Ignorer"],
    actionsNote: "Les boutons Valider, Modifier et Ignorer sont inactifs : le moteur de commentaires n'est pas encore connecté.",
    author: "Auteur",
    date: "Date",
    video: "Vidéo",
    priority: (score: number | null) => (score === null ? "Priorité —" : `Priorité ${score}`),
    proposedReply: "Réponse proposée",
    unknownVideo: "Vidéo inconnue",
    states: {
      ingested: "En attente",
      classified: "En attente",
      prioritized: "Prioritaire",
      contextualized: "Vérification",
      fact_checked: "Vérification",
      proposed: "Réponse proposée",
      in_review: "En validation",
      approved: "Approuvé",
      published: "Publié",
    } as Record<string, string>,
  },
  analytics: {
    kicker: "Performance",
    title: "Analytiques",
    description: "Cartes prêtes pour les données YouTube. L'API n'est pas connectée : aucune valeur n'est affichée ni estimée.",
    badge: "API YouTube : non connectée",
    kpis: [
      ["ctr", "CTR"],
      ["views", "Vues"],
      ["watch_time", "Temps de visionnage"],
      ["subscribers", "Abonnés"],
      ["retention", "Rétention"],
      ["rpm", "RPM"],
      ["revenue", "Revenus"],
    ] as const,
    top: "Meilleures vidéos",
    worst: "Vidéos les moins performantes",
    listHint: "Disponible une fois l'API d'analytiques connectée.",
  },
  learning: {
    kicker: "Amélioration continue",
    title: "Apprentissage",
    description: "Vue en lecture seule de la manière dont Nomad Studio apprend. La validation reste toujours humaine.",
    badge: "Lecture seule",
    timelineLabel: "Chronologie de l'apprentissage",
    stages: ["Observations", "Éléments de preuve", "Validées", "Appliquées", "Évolution des prompts"] as const,
    notTracked: "Pas encore suivi",
    lists: {
      observations: ["Observations", "Aucune observation enregistrée."],
      validated: ["Validées", "Aucun apprentissage validé pour le moment."],
      prompts: ["Évolution des prompts", "Aucune évolution de prompt proposée."],
    } as Record<string, [string, string]>,
    knowledge: "Connaissances",
    knowledgeOk: (n: number) => `${n} document(s)`,
    knowledgeEmpty: "Vide",
    knowledgeOkText: "Base de connaissances indexée par l'agent.",
    knowledgeEmptyText: "Aucun document de connaissance n'est encore indexé.",
    noText: "(sans texte)",
  },
  planner: {
    kicker: "Prochaine action",
    title: "Planificateur",
    description: "Quelle vidéo traiter ensuite, avec son échéance, ses blocages et les validations encore à venir.",
    emptyTitle: "Rien à planifier",
    emptyHint: "Liez une production à une vidéo : elle apparaîtra ici.",
    nextVideo: "Prochaine vidéo",
    progress: "Progression",
    remainingStages: (n: number) => `${n} étape(s) restante(s)`,
    priority: "Priorité",
    priorityValue: "Non définie",
    priorityNote: "Aucun champ de priorité n'existe encore.",
    deadline: "Échéance",
    estimated: "Fin estimée",
    estimatedNote: "Nécessite un historique des durées de production, qui n'est pas encore enregistré.",
    approvals: "Validations restantes",
    approvalsNote: "Validations humaines encore à venir pour cette vidéo.",
    blockers: "Blocages",
    noBlockers: "Aucun blocage détecté.",
    blockerLabels: {
      locked: "Production verrouillée (exécution en cours ou interrompue)",
      stage_failed: "Une étape du pipeline est en échec",
      approval_required: "Validation humaine requise avant la prochaine étape",
      no_target_date: "Aucune date prévue",
    } as Record<string, string>,
    blockerFallback: "Blocage détecté",
    recommendationOnly: "Simple recommandation : Nomad Studio n'exécute aucune étape.",
    queue: "File d'attente",
    queueEmpty: "Aucune autre vidéo en attente.",
    queueItem: (deadline: string, blockers: number, percent: number) => `Échéance ${deadline} · ${blockers} blocage(s) · ${percent} %`,
    actions: {
      run: "Lancer l'étape suivante",
      wait: "Attendre la fin de l'étape en cours",
      review_failure_then_resume: "Analyser l'échec, puis reprendre",
      prepare_publication: "Préparer la publication (manuelle)",
    } as Record<string, string>,
  },
  journal: {
    kicker: "Piste d'audit",
    title: "Journal",
    description: "Historique chronologique des actions enregistrées par l'agent, de la plus récente à la plus ancienne.",
    ariaTimeline: "Chronologie du journal",
    emptyTitle: "Aucune action enregistrée",
    emptyHint: "Le journal se remplit dès qu'une action est effectuée (lien vidéo, transition d'épisode…).",
    action: "Action",
    result: "Résultat",
    human: "Humain",
    agent: "Agent",
    approved: "Approuvé",
    noValidation: "Sans validation",
  },
  settings: {
    kicker: "Configuration",
    title: "Paramètres",
    description: "Lecture seule. La configuration se modifie dans le projet usine-ia-video.",
    badge: "Lecture seule",
    groups: { channel: "Canal", production: "Production", security: "Sécurité" },
    rows: {
      channel: "Canal",
      language: "Langue",
      style: "Style de rédaction",
      voice: "Voix ElevenLabs",
      workflow: "Workflow",
      comments: "Commentaires",
      publication: "Publication",
    },
    notDefined: "Non défini",
    notConfigured: "Non configurée",
    french: "Français",
    transitions: (n: number) => `${n} transitions`,
    approvals: (n: number) => `${n} nécessitent une validation humaine`,
    commentsValue: "Validation humaine obligatoire",
    commentsNote: "Réponses automatiques désactivées · ingestion non connectée",
    publicationNotConnected: "Non connectée",
    publicationNote: "Validation humaine requise",
  },
  diagnostic: {
    kicker: "Diagnostic de connexion",
    title: "Nomad Studio indisponible",
    text: "Nomad Studio nécessite que l'Usine IA Vidéo soit démarrée sur cet ordinateur.",
    retry: "Relancer le diagnostic",
    retrying: "Vérification…",
    likelyCause: "Cause probable",
    cause: "Cause",
    action: "Action corrective",
    checksLabel: "Vérifications du diagnostic",
    skippedNote: "Non vérifié : une étape précédente a échoué.",
    localAgent: "Agent local",
    lastCheck: "Dernière vérification",
    latency: "Latence",
    environment: "Environnement",
    rows: [
      ["bridge", "Pont local"],
      ["authentication", "Authentification"],
      ["configuration", "Configuration"],
      ["reachability", "Agent"],
      ["data", "Workflow"],
      ["contract", "Version"],
    ] as const,
    states: { ok: "OK", warn: "Attention", fail: "Erreur", skipped: "Non vérifié" } as Record<string, string>,
    agentUnavailable: "Indisponible",
    agentConnected: "Connecté",
  },
  errors: {
    denied: "Accès refusé.",
    server: "Le serveur Norixo n'a pas pu répondre.",
    unexpected: "Erreur inattendue.",
    retry: "Réessayer",
  },
  sectionUnavailable: "Section indisponible",
  sectionKinds: {
    not_configured: "agent non configuré",
    invalid_config: "configuration invalide",
    unreachable: "agent injoignable",
    timeout: "délai dépassé",
    host_rejected: "adresse refusée",
    origin_rejected: "origine refusée",
    bridge_disabled: "pont désactivé",
    unauthorized: "jeton refusé",
    bad_response: "réponse invalide",
    contract_mismatch: "version incompatible",
    agent_error: "erreur de l'agent",
  } as Record<string, string>,
  sectionHint: "Relancez le diagnostic pour en connaître la cause.",
} as const;

export const WORKFLOW_LABELS: Record<string, string> = {
  idea: "Idée",
  in_production: "En production",
  paused: "En pause",
  failed: "En échec",
  quality_passed: "Qualité validée",
  ready_to_publish: "Prête à publier",
  published: "Publiée",
  tracking: "Suivie",
  archived: "Archivée",
};

const OUTCOME_LABELS: Record<string, string> = {
  applied: "Appliquée",
  real: "Production réelle",
  test: "Production de test",
  approval_missing: "Validation manquante",
  approval_expired: "Validation expirée",
  action_mismatch: "Validation non conforme",
  approver_not_human: "Validation non humaine",
  not_approved: "Non approuvée",
  transition_not_allowed: "Transition non autorisée",
  unknown_state: "État inconnu",
  not_executable_in_r18_2: "Exécution non autorisée",
  engine_not_implemented: "Moteur non implémenté",
  unknown_engine: "Moteur inconnu",
};

export function journalActionLabel(entry: { type: string; action: string }): string {
  if (entry.type === "video_linked") return "Vidéo liée à une production";
  if (entry.type === "execute_refused") return "Exécution refusée";
  if (entry.type === "workflow_refused") return "Transition refusée";

  if (entry.type === "workflow_transition") {
    const [from, to] = entry.action.split("->");

    return `Transition : ${WORKFLOW_LABELS[from] ?? "?"} → ${WORKFLOW_LABELS[to] ?? "?"}`;
  }

  return "Action enregistrée";
}

export function journalOutcomeLabel(outcome: string | null): string {
  if (!outcome) return "—";

  return OUTCOME_LABELS[outcome] ?? "Enregistré";
}
