import { NextRequest, NextResponse } from "next/server";
import { isAdminPrivateEmail } from "@/lib/auth/isAdminEmail";
import { getBacklinkOutreachById, getActiveBacklinkOutreachByIdentity, updateBacklinkOutreach } from "@/lib/backlinks/repositories/outreachRepository";
import { getBacklinkContactById, listBacklinkContactsByDomain } from "@/lib/backlinks/repositories/contactsRepository";
import { getBacklinkOpportunityById } from "@/lib/backlinks/repositories/opportunitiesRepository";
import { getCampaignOpportunity } from "@/lib/backlinks/repositories/campaignOpportunitiesRepository";
import { listBacklinkOutreachByOpportunity } from "@/lib/backlinks/repositories/outreachRepository";
import { updateBacklinkOutreachDraft } from "@/lib/backlinks/services/outreachDraftEditService";
import { getRequestUserAndWorkspace } from "@/lib/server/routeAuth";
const channels = ["email", "linkedin", "contact_form"] as const;
function parse(value: unknown) { if (typeof value !== "object" || value == null || Array.isArray(value)) return null; const r = value as Record<string, unknown>; const keys = Object.keys(r); return keys.length === 4 && ["subject", "body", "contactId", "channel"].every((key) => keys.includes(key)) && (typeof r.subject === "string" || r.subject === null) && (typeof r.body === "string" || r.body === null) && typeof r.contactId === "string" && channels.includes(r.channel as typeof channels[number]) ? { subject: r.subject, body: r.body, contactId: r.contactId, channel: r.channel as typeof channels[number] } : null; }
export async function PATCH(request: NextRequest, context: { params: Promise<{ id: string }> }) { const auth = await getRequestUserAndWorkspace(request); if (auth.status === "unauthenticated") return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (auth.status === "workspace_forbidden" || !isAdminPrivateEmail(auth.user.email)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const input = parse(await request.json().catch(() => null)); if (!input) return NextResponse.json({ error: "Invalid request body" }, { status: 400 }); const { id } = await context.params; try { const result = await updateBacklinkOutreachDraft({ eligibility: { getMembership: (value) => getCampaignOpportunity(auth.client, value.workspaceId, value.campaignId, value.opportunityId), getOpportunity: (workspaceId, opportunityId) => getBacklinkOpportunityById(auth.client, workspaceId, opportunityId), listContactsByDomain: (workspaceId, domainId) => listBacklinkContactsByDomain(auth.client, workspaceId, domainId), listOutreachByOpportunity: (workspaceId, opportunityId) => listBacklinkOutreachByOpportunity(auth.client, workspaceId, opportunityId) }, getOutreach: (workspaceId, outreachId) => getBacklinkOutreachById(auth.client, workspaceId, outreachId), getContact: (workspaceId, contactId) => getBacklinkContactById(auth.client, workspaceId, contactId), getActiveOutreach: (value) => getActiveBacklinkOutreachByIdentity(auth.client, value), updateOutreach: (workspaceId, outreachId, value) => updateBacklinkOutreach(auth.client, workspaceId, outreachId, value) })({ ...input, workspaceId: auth.workspace.id, actorUserId: auth.user.id, outreachId: id }); return NextResponse.json({ ok: true, result }); } catch { return NextResponse.json({ error: "Draft update unavailable." }, { status: 409 }); } }
