import type { MarketingAiAgentDefinition } from "./agentTypes";

export const MARKETING_AI_AGENT_REGISTRY: MarketingAiAgentDefinition[] = [
  {
    id: "marketing-brain",
    name: "Marketing Brain",
    role: "Décision stratégique",
    description: "Agent prévu pour analyser les objectifs business et arbitrer les priorités marketing.",
    status: "simulation",
    requiredCapabilities: ["chat", "analytics"],
    preferredProviderIds: ["openai", "anthropic", "google"],
    preferredModels: ["GPT-5.5", "Claude Sonnet", "Gemini 2.5 Pro"],
    inputType: "Objectifs business, contexte produit, priorités",
    outputType: "Brief stratégique et arbitrages",
    isExecutable: false,
  },
  {
    id: "campaign",
    name: "Campaign",
    role: "Orchestration des campagnes",
    description: "Agent prévu pour transformer un brief en plan de campagne structuré.",
    status: "read_only",
    requiredCapabilities: ["chat"],
    preferredProviderIds: ["openai", "anthropic"],
    preferredModels: ["GPT-5.5", "Claude Sonnet"],
    inputType: "Brief stratégique",
    outputType: "Plan de campagne structuré",
    isExecutable: false,
  },
  {
    id: "content",
    name: "Content",
    role: "Production éditoriale",
    description: "Agent prévu pour produire les contenus marketing sources et leurs variations.",
    status: "simulation",
    requiredCapabilities: ["chat", "translation"],
    preferredProviderIds: ["openai", "anthropic"],
    preferredModels: ["GPT-5.5", "Claude Sonnet"],
    inputType: "Plan de campagne",
    outputType: "Contenu source et variations",
    isExecutable: false,
  },
  {
    id: "localization",
    name: "Localization",
    role: "Adaptation multilingue",
    description: "Agent prévu pour adapter les contenus aux langues et contextes locaux.",
    status: "simulation",
    requiredCapabilities: ["translation", "chat"],
    preferredProviderIds: ["openai", "google", "anthropic"],
    preferredModels: ["GPT-5.5", "Gemini 2.5 Pro", "Claude Sonnet"],
    inputType: "Contenu source",
    outputType: "Versions localisées",
    isExecutable: false,
  },
  {
    id: "image",
    name: "Image",
    role: "Création visuelle",
    description: "Agent prévu pour générer ou préparer des assets visuels marketing.",
    status: "not_active",
    requiredCapabilities: ["image"],
    preferredProviderIds: ["openai"],
    preferredModels: ["GPT Image"],
    inputType: "Prompts visuels et guidelines",
    outputType: "Assets image prêts à valider",
    isExecutable: false,
  },
  {
    id: "video",
    name: "Video",
    role: "Création vidéo",
    description: "Agent prévu pour préparer scripts, storyboards et assets vidéo.",
    status: "not_active",
    requiredCapabilities: ["video", "audio"],
    preferredProviderIds: ["google", "openai"],
    preferredModels: ["Veo", "OpenAI TTS"],
    inputType: "Storyboard, voix, visuels",
    outputType: "Vidéo marketing préparée",
    isExecutable: false,
  },
  {
    id: "publication",
    name: "Publication",
    role: "Diffusion contrôlée",
    description: "Agent prévu pour préparer les publications sociales et email sous validation humaine.",
    status: "not_active",
    requiredCapabilities: ["socialPublishing", "emailCampaigns"],
    preferredProviderIds: ["meta", "brevo"],
    preferredModels: [],
    inputType: "Contenus validés",
    outputType: "Publications planifiées",
    isExecutable: false,
  },
  {
    id: "analytics",
    name: "Analytics",
    role: "Mesure de performance",
    description: "Agent prévu pour lire les résultats, signaux et recommandations marketing.",
    status: "read_only",
    requiredCapabilities: ["analytics"],
    preferredProviderIds: ["google", "meta", "brevo"],
    preferredModels: [],
    inputType: "Résultats et signaux",
    outputType: "Indicateurs et recommandations",
    isExecutable: false,
  },
  {
    id: "learning",
    name: "Learning",
    role: "Amélioration continue",
    description: "Agent prévu pour transformer les retours analytics en apprentissages actionnables.",
    status: "planned",
    requiredCapabilities: ["analytics", "chat"],
    preferredProviderIds: ["openai", "anthropic", "google"],
    preferredModels: ["GPT-5.5", "Claude Sonnet", "Gemini 2.5 Pro"],
    inputType: "Résultats analytics",
    outputType: "Ajustements futurs",
    isExecutable: false,
  },
];
