import type { MarketingAiProviderDefinition } from "./providerTypes";

export const MARKETING_AI_PROVIDER_REGISTRY: MarketingAiProviderDefinition[] = [
  {
    id: "openai",
    name: "OpenAI",
    category: ["llm", "image", "audio"],
    status: "not_connected",
    capabilities: ["chat", "image", "audio", "embeddings", "moderation", "translation"],
    models: ["GPT-5.5", "GPT-5.5 mini", "GPT Image", "OpenAI TTS"],
    description: "Provider prévu pour les contenus, prompts, images, voix et contrôles qualité.",
    isConnected: false,
  },
  {
    id: "anthropic",
    name: "Anthropic",
    category: ["llm"],
    status: "not_connected",
    capabilities: ["chat", "translation"],
    models: ["Claude Sonnet", "Claude Opus"],
    description: "Provider prévu pour la rédaction longue, le raisonnement et la QA éditoriale.",
    isConnected: false,
  },
  {
    id: "google",
    name: "Google",
    category: ["llm", "video", "analytics"],
    status: "not_connected",
    capabilities: ["chat", "video", "analytics", "translation"],
    models: ["Gemini 2.5 Pro", "Gemini Flash", "Veo"],
    description: "Provider prévu pour les usages multimodaux, vidéo et analytics futurs.",
    isConnected: false,
  },
  {
    id: "xai",
    name: "xAI",
    category: ["llm"],
    status: "planned",
    capabilities: ["chat", "analytics"],
    models: ["Grok"],
    description: "Provider prévu pour la veille et l'analyse temps réel future.",
    isConnected: false,
  },
  {
    id: "meta",
    name: "Meta",
    category: ["social", "analytics"],
    status: "not_connected",
    capabilities: ["socialPublishing", "analytics"],
    models: [],
    description: "Provider prévu pour Facebook, Instagram, pages, publications et analytics sociaux.",
    isConnected: false,
  },
  {
    id: "brevo",
    name: "Brevo",
    category: ["email", "analytics"],
    status: "not_connected",
    capabilities: ["emailCampaigns", "analytics"],
    models: [],
    description: "Provider prévu pour les campagnes email, notifications et statistiques email.",
    isConnected: false,
  },
];
